### PR TITLE
Wip database

### PR DESCRIPTION
**Pull request by Smeulf**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Improvements

Commit 1:
- Rework library so remove_item no longer uses metadata
- Other library improvments

Commit 2:
- Fix db_shared overrides

Commit 3:
- Reintroduce "Fix Upnext" for watched status from library

Commit 4:
- Display progress bar when exporting new episodes manually

Commit 5:

- Import old library to new one at addon upgrade

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
thanks for the fixes!

**Comment by Smeulf** [comment]
@CastagnaIT As said, I used the upgrade_controller to perform the database migration from old format.

Main problem for me: the upgrade still runs at addon.py, not service.py. I still think we should have it at the service level... but that will be your call.

**Comment by CastagnaIT** [comment]
> @CastagnaIT As said, I used the upgrade_controller to perform the database migration from old format.
> 
> Main problem for me: the upgrade still runs at addon.py, not service.py. I still think we should have it at the service level... but that will be your call.

for this purpose tomorrow i will make more logical changes, i will modify the my old commits

I imported your commits and split them into multiple commits, where possible keep the changes on multiple commits
I also made some small changes

**Comment by Smeulf** [comment]
Fine for me, I'll run some more tests tomorrow. And again before we merge the branch to master.

You really don't want the upnext fix? ^^

**Comment by notoco** [comment]
Yeah,... Realy?

**Comment by CastagnaIT** [comment]
it is absolutely not intentional to exclude it i was too tired last night, today i try to do last things

**Comment by Smeulf** [comment]
May I close PR and delete the branch?

**Comment by CastagnaIT** [comment]
yes here all is done

**Pull request closed without merging**
