### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by notoco**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
need to fix n°:
30064
30180

**Comment by CastagnaIT** [comment]
i'm sorry but can't merge, you need to rebase your branch

**Comment by notoco** [comment]
And here comes my poor knowledge of github. I'll try later

**Comment by notoco** [comment]
Does not matter. I don't understand github enough, much less GithubDesktop. Maybe it will be easier to get this commit and issue a new one, 100% correct?

**Comment by CastagnaIT** [comment]
mmh yes i think it's easier for you to close your open PRs and create a new one..

**Comment by notoco** [comment]
Cóż... Nikt nie jest doskonały...
So... Nobody's perfect... :)

**Pull request closed without merging**
