### PR TITLE
Ensure only PRs and pushes to master are tested

### PR DESCRIPTION
**Pull request by dagwieers**
This prevents from doing the same tests twice for other branches in the
same repository.

### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by dagwieers** [comment]
So this is more what we would expect.

**Comment by dagwieers** [comment]
@CastagnaIT If you fix the Python 3.8 issue, we can also enable Python 3.8 testing. And as soon as we have all dependencies in Matrix, we can also enable Matrix-testing.

I also think we need to enable the integration tests and coverage. For this you would need to add your credentials as a secret in GitHub (ADDON_USERNAME and ADDON_PASSWORD). Once these are available, I can modify the CI workflow to add those test and integrate coverage.

**Comment by CastagnaIT** [comment]
is for the `clock` function problem right? i will look at
I think it can be easily replaced with `time`
but at the moment I'm busy with a big experiment related to the cache
so if there is no urgency any changes to the code remain suspended

**Comment by CastagnaIT** [comment]
for coverage i won't put in my credentials in to coverage system, i want avoid to get my account banned

**Comment by dagwieers** [comment]
> for coverage i won't put in my credentials in to coverage system, i want avoid to get my account banned

Ok, but it means we cannot perform integration tests that require Netflix services. But we could be adding unit tests for all internal functionality (or uses stub payload instead of Netflix services).

**Pull request merged**
