### PR TITLE
Update Romanian strings

### PR DESCRIPTION
**Pull request by tmihai20**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by tmihai20** [comment]
I do not know why there are 8 commits (there should be just 2). I did pull the latest changes from your project and then made 2 new commits.

**Comment by CastagnaIT** [comment]
because you're using github the wrong way
your master branch must always be synchronized with my master branch

before you modify anything, you must create a copy of your master branch under a different name
like "translation"

then make the changes in the "translation" branch and create a PR with this branch, not with  "master" branch

**Comment by CastagnaIT** [comment]
I can't merge this PR, too confused

**Comment by tmihai20** [comment]
I have done this before on many projects, yours seems to be the only one that is showing the already merged commits. It may have something to do with the fact that you force pushed some of the changes and you did not pick up mine. It is recommended to not do force push as it can lead to situations like this one. You should have waited until I had modified the file as you wanted. I will not delete my fork as I want my history. Tell me how can I modify the Romanian strings without deleting my existing fork?

**Comment by CastagnaIT** [comment]
as you can see i have merge your previous PR like "squash & merge" and not directly "merge" method
git doesn't recognize your branches as exact to mine, so it proposes to add also the commits that are not included in the content

this is why the master branch should never be modified if you are working on external projects
so should be updated before any future changes.

but don't come in here and tell me i did something wrong, you are clearly misusing github,
i explained the right method to you, as it is explained on any git guide

if you try to do same thing in the e.g. Kodi github project, you will be warned by the Kodi developers for misuse of git.

so, in order not to lose your previous commits you have to do a copy your master branch to another name with `git checkout -b anothernamebranch` command

then get the list of commits SHA `git log` and take note of your commit SHA to keep

return to master branch and force sync
then copy it to another name `git checkout -b mychanges`
and cherry-pick the previous commit: `git cherry-pick THESHA`

**Pull request closed without merging**
