### PR TITLE
Revision of the Readme

### PR DESCRIPTION
**Pull request by CastagnaIT**
Updates and changes to the readme

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@Smeulf
If you can do a quick check on what i wrote, in case you make changes
if there is a need for other updates to the readme propose otherwise i close with this

**Comment by Smeulf** [comment]
Looks good to me.
We'll see if a question comes often.

**Comment by Smeulf** [comment]
Maybe we should add something about the library path in case it's shared:
It MUST be the EXACT same path on both devices, or it won't work.

**Comment by Smeulf** [comment]
Change proposal: https://github.com/CastagnaIT/plugin.video.netflix/pull/165

**Pull request closed without merging**
