### PR TITLE
Joining of all servers

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

...one server to rule them all...

This change is partially due to the latest changes to fix HTTP errors (ref #1065),
we currently have two opened web sessions (one on MSL, one on NFSession) and there should only be one,
these changes involve:
- New multithreaded service server (capable to handle multiple requests at same time)
- Single web session for both (MSL/NFSession)
- Removing of some "service to service" IPC calls
- One server instead of 3 servers should free up more resources on low-end devices
- Made some parts of the code less complex

Possible side effects to be check:
- Requests module like any other HTTP module is not fully thread safe, sometimes could fails, but we not having to make many requests at the same time, it might be a very rare problem

### CODE REVIEW

**Comment by CastagnaIT** [comment]
hi @jakermx if you have time can you do some test with this branch? should be stable,
but could be happen unexpected things,
is needed also test sequential playlist video playback with or without UpNext

**Comment by CastagnaIT** [comment]
hi @wagnerch have you some time one day make some tests with this changes for Kodi 19?
other system than Windows 10 if possible

**Comment by jakermx** [comment]
Hi, I am at the hospital, since about 2 weeks ago,  I am ok now....

Tested on Linux on my laptop, without issues, and it looks fine the one server connection share  for msl and nfs
Tonight or Tomorrow, depending when  I can get out of the hospital, I will test it on Windows and RPI.

Greetings

**Comment by CastagnaIT** [comment]
@jakermx thankyou i wish you a good recovery

**Comment by jakermx** [comment]
On Windows looks pretty good, keep alives are working fine too...

**Comment by jakermx** [comment]
Another good thing is that Netflix Login with Email/Pass pair is working, at least I havent had to use Key Authentication on all my systems

**Comment by jakermx** [comment]
want me to check it on LibreELEC n RPi ,doesnt mind if it is on alpha version?

**Comment by wagnerch** [comment]
> hi @wagnerch have you some time one day make some tests with this changes for Kodi 19?
> other system than Windows 10 if possible

Sorry, no Kodi 19 here yet.

**Comment by jakermx** [comment]
@wagnerch  Mac?

**Comment by CastagnaIT** [comment]
it is true ATM only RPI4 seem works
but i think we can move forward
i have not experienced any problems at least with Windows in the last 4 days

**Comment by jakermx** [comment]
I have 2 RPI4B at home, I am using LibreElec Alpha and Ubuntu Mate , both seems to be working....I also Have a RPi Zero W, it does not play any video, due HW Features, but Session Handling looks fine so far... same  on T4L on Nvidia.

**Comment by jakermx** [comment]
I agreed, but I have a suggestion/consideration for better connection handling.

-Set the content tracking on by default
-Define a connection timeout after some idle time, this would apply if the user disable the content tracking off,because no MSL Event calls will be placed
-if content tracking option is off, the addon may close the nf base session connecction during playback after about 4 minutes it could be triggered by the Continuity Handler
-Add an Exception Handler if the tracking is on and the playback is done, so Percentage will be reported as 100%, in order to avoid out of range or none tyoe errors

And thats it, this way, you can take over the urllib, request and some other platform issues.

Take a look on https://github.com/cloudflare/cloudflare-blog/tree/master/2019-09-tcp-keepalives

But as you implemented a better Timeout Errors Handling, it is not imperative, but it would be nice and standard.


Finally, I would like to congratulate you, because, your PR on xbmc about TCP KeepAlive, was the only over about 10 addons that was expedited and it  is included on Kodi 19.0 Final Release Version...

**Comment by CastagnaIT** [comment]
> Set the content tracking on by default

what means exactly "content tracking"?

**Comment by jakermx** [comment]
Watched and Tracking sync

**Comment by CastagnaIT** [comment]
The use of TCP_USER_TIMEOUT is linux only
this command does not seem to be widely used on the net, seem only complicates things already complex

> Finally, I would like to congratulate you, because, your PR on xbmc about TCP KeepAlive, was the only over about 10 addons that was expedited and it is included on Kodi 19.0 Final Release Version...

After all, the problem was caused by a Kodi developer, fortunately they have included the update in the final version this is better thing for all people

The netflix sync being a complex system is not enabled by default, because could easily break down,
but since it has not given any particular troubles in about two years, could be enabled by default now

**Pull request merged**
