### PR TITLE
Small fixes after pylint/flake cleanup

### PR DESCRIPTION
**Pull request by dagwieers**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
After reviewing #194 after an issue (#217) was found, I found one other issue.
Which this PR fixes.

### CODE REVIEW

**Comment by Smeulf** [comment]
Got it!

In the former code, we were doing an action for mediatype=MOVIE or for mediatype=SHOW.
In your code before the fix, if the type is MOVIE, the code will jump to `for season_key in item.keys():` and run into an error.

So this fix is very right.

**Comment by dagwieers** [comment]
As most of the source code, annotations would be helpful 😉

**Comment by Smeulf** [comment]
I agree, and have to admit that piece of code I wrote was not a model of art...

**Comment by dagwieers** [comment]
@Smeulf There is no real issue with the code, but I learned earlier this year something called *return early* or *guard code* and it is something I unknowingly was practising already to keep indentation to a minimum (and readability to a maximum).

It is very pythonic and well-explained here: https://openfolder.sh/returning-early

**Comment by Smeulf** [comment]
And by extension, it reduced the code complexity if I'm correct.

**Pull request merged**
