### PR TITLE
Updated german translation

### PR DESCRIPTION
**Pull request by tweimer**
Addresses #306

### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
Updated translation, addresses #306

### CODE REVIEW

**Comment by CastagnaIT** [comment]
i wait to merge this,
there will be two other small changes soon
so you can directly include them

**Comment by tweimer** [comment]
@CastagnaIT That's fine. I have updated it with the latest changes.

**Comment by tweimer** [comment]
@CastagnaIT Merge conflicts resolved

**Comment by CastagnaIT** [comment]
thank you

**Pull request merged**
