### PR TITLE
The MSL switch profile

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

After more o less 8 hours of testing and network flow analisys and source code analysis
I was able to get the missing key of this project!

🎉🎉✨🎊🎁 **The MSL switch profile!** 🎉🎉✨🎊🎁

That's a big stone that's always been missing

**This solves many very very old problems, from the first version of this addon (13.x) developed by asciidisco**

Now being able to run this MSL switch, we can make MSL requests using actually the selected user profile!

What solves:
- The availability of audio languages will be correct, no more missing languages
- The availability of subtitle languages will be correct, no more missing languages
- Now requests from Kid profiles can actually be executed correctly
- Solved the problems of age limits set in the main profile but not in the others, that caused errors like video not available
- You can communicate the watched status of the watched videos in each profile!

Ref.
https://github.com/CastagnaIT/plugin.video.netflix/pull/385
https://github.com/CastagnaIT/plugin.video.netflix/issues/366

Due to major refactor to the code i could not make separate commits,
so to better understand the changes i will try to divide the refactor and the implementation into two commits

Due to the complexity of this implementation there will certainly be some errors overlooked, also because i don't have testers able to support me

Unresolved problem:
Progress sent by Kodi are not displayed on android, but only on the website,
seem that is the same problem of not updated continue watching list

### CODE REVIEW

**Comment by CastagnaIT** [comment]
**i need a volunteer to do a test on an android device**
i need a log debug, please do this steps:

-install Kodi from scratch
-Install this [plugin.video.netflix_0.16.4_20200222.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4239794/plugin.video.netflix_0.16.4_20200222.zip)
-Without login, open addon settings and on expert setting set debug verbose
-Remember to enable Kodi debug
-Reboot Kodi and wait nf service ready
-Attach here the verbose log

**Comment by Gelion01** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4240503/kodi.log)
Here you are.

**Comment by CastagnaIT** [comment]
Thank you!

**Comment by Gelion01** [comment]
[kodi_sync_main.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4241500/kodi_sync_main.log)
[kodi_sync_other.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4241501/kodi_sync_other.log)
[kodi_sync_other2.log](https://github.com/CastagnaIT/plugin.video.netflix/files/4241502/kodi_sync_other2.log)

I did the test with 2 non-main accounts, because on the first "other" account there was parallel playback on another device. I didn't want to screw up any results with this.

I don't know whether you are aware of this, but the continue watching playlist still doesn't get updated through the sync (TV series already in the list get updated internally, but they don't move up the list). Also, through the netflix android app, you're not able to see the progress already made when you are watching a movie. When you play it, you start off where you left with kodi. TV series are displayed differently because of their seasons. There is always a progress bar displayed at the episodes.
Within the browser, this isn't a problem, because a progress bar is always being displayed, no matter whether the movie is in the continue watching list or not.
I really appreciate your work and hope that I can be a little bit of a help with this.

**Comment by CastagnaIT** [comment]
>  don't know whether you are aware of this, but the continue watching playlist still doesn't get updated

Answer here: https://github.com/CastagnaIT/plugin.video.netflix/wiki/Sync-watched-status-with-Netflix

in relation to netflix android app,
i think the problem of not being able to visualize the progress made with Kodi is due to the same problem of continue watching list

there's no documentation on how these things work the only way is to experiment in the field
now that things are working better, i can try to reuse the refreshlolomo path again

Fixing this last thing is the only thing missing to have everything working almost perfectly

**Pull request merged**
