### PR TITLE
Rework for new website endpoints

### LINKED ISSUE #1424: MSL Error user authentication data does not match entity identity on L3 device
### Netflix add-on version

version 1.18.10

### Operative systems used

Android

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I can loggin to netflix addon but when i try to watch a movie this erros appears: "MSL Error user authentication data does not match entity identity"

It works fine on previous version

### Steps to reproduce the behavior

_No response_

### Debug log - mandatory

https://paste.kodi.tv/uzoqadaxaj.kodi

### Possible fix

_No response_

### Additional context

_No response_

### Screenshots

_No response_

### LINKED ISSUE #1425: TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'
### Netflix add-on version

1.18.10

### Operative systems used

Windows

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I open Netflix addon and when i press to select my profile i get the following error:

TypeError: __init__() missing 2 required keyword-only arguments: 'request' and 'response'

I also tried to open the addon from the Settings, Addons, My addons, Video addons menu, with the same result

### Steps to reproduce the behavior

Open Netflix addon
Press to select profile

### Debug log - mandatory

https://paste.kodi.tv/ukugisozor.kodi

### Possible fix

_No response_

### Additional context

_No response_

### Screenshots

_No response_

### LINKED ISSUE #1428: Plugin HTTP Error - 404 Client Error: Not Found for url
### Netflix add-on version

1.12.14

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When the plugin is open and it should show the list of media content, it returns the error:
`404 Client Error: Not Found for url: https://www.netflix.com/api/shakti/vedfdb694/pathEvaluator?materialize=false&original_path=%2Fshakti%2Fvedfdb694%2FpathEvaluator&categoryCraversEnabled=false&isVolatileBillboardsEnabled=true&isTop10Supported=true&routeAPIRequestsThroughFTL=false&withSize=false&drmSystem=widevine`

Note: Authentication key is used as authentication method. The plugin worked fine yesterday but today got this error. Rebooting the system nor re authenticating did not solve the problem.

### Steps to reproduce the behavior

1. Go to Add-on and open Netflix addon
2. The account main menu is shown, with the account name and the "Children" menu items.
3. Click on the account name to access the content -> The "404 Client Error: Not Found for url" is returned

### Debug log - mandatory

https://paste.kodi.tv/bacicebiko.kodi

### Possible fix

_No response_

### Additional context

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which changes behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactor (non-breaking performance or readability improvements)

### Description

In the last few days there are new changes in website that has full broken the addon,
the new endpoints caused to force also the use of JSONGraph data to http responses making the use of `falcor_server` request header useless

last day (30/09) they seem to have enabled the old endpoints again, but this back-and-forth situation is not clear,
to be aligned with the website now we support to read data as JSONGraph format by using also `falcor_server` header,
this is a quick adaptation in the future the handling of JSONGraph data via an ad-hoc class could be evaluated

Fix #1425
Fix #1428

This PR include also a specifics change for Android L3 devices, a followup fix of #1415 
`NETFLIXID` auth at today not works with Android L3 devices so ATM we are forced to use `EMAIL_PASSWORD` / `USER_ID_TOKEN` auth ofc without `SWITCH_PROFILE`.
_Due to this for these L3 devices will be possible play videos only from main/owner profile_, because we miss a way to switch MSL profile.

Fix #1424

### CODE REVIEW

**Comment by 72ka** [comment]
Interresting, the issue is fixed by this pull request on my coreELEC but every video freezes after around two minutes of playing... Have anoyone the same issue?

**Comment by UUInc-co** [comment]
Hey @72ka, my apologies as this most likely wont be super helpful. But to answer your question, I personally haven't had any of my video's freeze @ ~2min. I too pulled down this **pr** to test out @CastagnaIT's fix for the login/user selection issue. After pulling the PR down, clearing my cache and a reboot, I could now login, select a user in the account and play some videos. 

#### RE:Checking for freezing video's
I was only clicking play and watching the video's for a couple seconds to test. Knowing about your issue I am now running a longer set of tests, and so far all 6 video's have played successfully for at least 10 minutes before I've stopped them. 

I also tried to load coreELEC on a machine to test with that instead of OSMC. However, I borked the install and gave up for now  as I need a nap. Sorry. 

#### //Versions: 
**OSMC** - 2022.09-1
**Kodi** - 19.4
**Plugin.Video.Netflix** - 1.18.10+matrix.1 
**Branch** - [rework_endpoints](https://github.com/CastagnaIT/plugin.video.netflix/tree/rework_endpoints)

#### //@CastagnaIT: 
I am not sure how often you hear this, but you my my man are a freakin' legend. Thank you so much for the quick fix to this issue. Not to mention the continous work you do on this repo. If there is every anything I can do, please let me know!  Cheers!

**Comment by UUInc-co** [comment]
Just in case this helps anyone.  

Right when the video's freeze for me at the 2 min mark, the following errors pop up in kodi's log file (~/.kodi/temp/kodi.log). 
I am not sure if it's 100% related as I am way too sleepy atm. But looked like it could be important.   

#### //Logs @ Freeze

> 
> 2022-10-01 08:29:12.321 T:1063    ERROR <general>: Window Translator: Can't find window True
> 2022-10-01 08:30:10.509 T:5119    ERROR <general>: Skipped 1 duplicate messages..
> 2022-10-01 08:30:10.509 T:5119    ERROR <general>: AddOnLog: inputstream.adaptive: DecodeVideo: kNoKey for key 0000000006542EAA0000000000000000
> 2022-10-01 08:30:12.133 T:1138     INFO <general>: Skipped 237 duplicate messages..
> 2022-10-01 08:30:12.133 T:1138     INFO <general>: [plugin.video.netflix (0)] EVENT [keepAlive] - Executing request
> 2022-10-01 08:30:12.178 T:5119    ERROR <general>: AddOnLog: inputstream.adaptive: DecodeVideo: kNoKey for key 0000000006542EAA0000000000000000
> 2022-10-01 08:30:22.188 T:5119    ERROR <general>: Skipped 239 duplicate messages..
> 2022-10-01 08:30:22.187 T:5119    ERROR <general>: AddOnLog: inputstream.adaptive: DecodeVideo: kNoKey for key 0000000006542EAA0000000000000000

**Comment by netzmark** [comment]
Any chance to have this bug fix applied to the Leia branch?

**Comment by CastagnaIT** [comment]
Sorry guys i want keep the PR clean so i deleted your comments, all your answers are in Issue #1425

Users are allowed to comment on a PR only for development purpose
all other use cases please use threads in "Issues" or "Discussions" pages

**Pull request merged**
