### PR TITLE
Update French translation for v1.14.0

### PR DESCRIPTION
**Pull request by thombet**
See #306

### CODE REVIEW

**Comment by thombet** [comment]
@CastagnaIT I am not able to run the add-on on Matrix for now so I was not able to check how the strings to translate are actually used.

For instance for strings 30039 you added the `ID` substring: does it mean that the parameter which uses 300039 has a different value than in v1.13.0? If the value is the same as in v1.13.0 I think I will reuse the same translation as in v1.13.0 because it was shorter.

**Comment by CastagnaIT** [comment]
As I have removed the double menu, it is no longer specified that it is the view's ID value
then i have add the ID word

**Comment by thombet** [comment]
@CastagnaIT 
> As I have removed the double menu, it is no longer specified that it is the view's ID value
> then i have add the ID word
> a short version should be better, but i do not know what it is better for your language

Thanks for the clarification. I think mentionning the "ID" is probably better in French too as it will limit the confusion.
I think I will be able to check on Matrix if it is too long for the next release. If it is I will update these strings.

**Comment by CastagnaIT** [comment]
it is good thanks

**Pull request merged**
