### PR TITLE
:bug: - Add back ListItem.Title

### LINKED ISSUE #680: [Bug] ListItem.Title no Longer Being Filled?
#### Your Environment
- Netflix add-on version: 1.4.0
- Operating system version/name: Windows 10

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug
`ListItem.Title` doesn't appear to be filled on any content from the add-on.

#### Expected behavior
`ListItem.Title` should have a value wherever it is loaded inside Kodi.

#### Actual behavior
`ListItem.Title` doesn't have a value on any items in the add-on.

#### Steps to reproduce the behavior
1. Focus an item in the Netflix add-on.
2. Attempt to read `ListItem.Title`, using whichever method you prefer. I used Devhelper Web.

### Debug log
The debug log can be found from this link: https://pastebin.com/rA85Pd3E

#### Other information
I've so far tested this on Arctic Zephyr 2 and Arctic Horizon.

### PR DESCRIPTION
**Pull request by drinfernoo**
Close #680

### CODE REVIEW

**Comment by CastagnaIT** [comment]
is not only this is need to be handled also the cases of tvshow/movie titles highlight

**Comment by CastagnaIT** [comment]
ah you changed the way I have to look better

**Comment by drinfernoo** [comment]
Do I need to make any changes?

**Comment by CastagnaIT** [comment]
i preefer maintain untouched the _convert_dict_to_listitem method
your way affect not only directory but also items in the custom xml windows

the same thing and i think more cleaning is do the change in infolabels.py
by removing this:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/kodi/infolabels.py#L62-L63

and so add this line:
`infos_copy['title'] = dict_item['label']`
before this line:
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/kodi/infolabels.py#L80

in this way are excluded the listitems in xml windows, and also directories that have not involved videoid data

**Comment by CastagnaIT** [comment]
you can also remove the argument `include_title=False` from `get_info` method and fix related calls to this method

**Comment by drinfernoo** [comment]
I'll take a look at making those changes this evening.

**Comment by CastagnaIT** [comment]
because with some type of ListItem kodi replace `Label `value with `Title` of infolabel
and this will broken the highlight colors of listitem's

so at this point we remove the conditions so the code becomes less complex

**Comment by drinfernoo** [comment]
I believe I've now made the requested changes 👌

**Comment by CastagnaIT** [comment]
go well, next time you can delete unuseful commits

**Comment by drinfernoo** [comment]
I've squashed my newest commits.

**Pull request merged**
