### PR TITLE
Changes to work with the new "loco" lists

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Netflix has rollout the new "loco" list system to all countries and the "lolomo" seem now deprecated
Therefore are needed to do checks and changes to various code

Issue: https://github.com/CastagnaIT/plugin.video.netflix/issues/701

### CODE REVIEW

**Comment by stevenhoving** [comment]
I just tested your changes successfully

**Comment by shtrom** [comment]
:heavy_check_mark: I just tested the changes successfully by replacing the addon from the repo with a zip from this PR.

**Comment by obaceski** [comment]
I tested the patch on top of the latest add-on version and now the keyerror is fixed and video plays as usual

**Comment by frantiseksidak** [comment]
> 
> 
> I tested the patch on top of the latest add-on version and now the keyerror is fixed and video plays as usual

Same here (libreelec, kodi 18, Czech Republic)

**Pull request merged**
