### PR TITLE
Reworked addon auto-configuration and improvements

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Improved the auto configuration of the addon,
in the hope that users encounter fewer configuration problems especially for android 4K devices

~It will also automate the HDR option, taking advantage of Kodi's pre-existing setting~

To get this merged, is needed to wait:
- next release of script.module.inputstreamhelper, that fixes a critical bug
- ~have implemented the PR to get the status of HDR Kodi setting~

it seems that Kodi developers will make us wait a long time before allowing the reading of this property (HDR settings), i will have to leave it in ToDo again for an uncertain future
ref. https://github.com/xbmc/xbmc/pull/17280

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@dagwieers please can you test this on RPI?

I've added a check to automatically disable OMXPlayer when it is enabled before playback, and after stop the playback it will be automatically reenabled.
ref. https://github.com/CastagnaIT/plugin.video.netflix/issues/471

_attention you can use it as update, but, this test includes all the latest MSL updates in WIP, if you prefer you can make a backup of your data_

[plugin.video.netflix_0.16.4_20200223_test1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4241044/plugin.video.netflix_0.16.4_20200223_test1.zip)

(yes this PR is not updated yet, is needed the other PR opened)

**Comment by dagwieers** [comment]
Sorry @CastagnaIT I really wanted to test this and give feedback, but I started a new job last week and have not had the time or energy to work on this.

**Comment by CastagnaIT** [comment]
I tried..quiet.. but i had to merge it i have too many things which i'm developing was starting to get difficult

**Comment by dagwieers** [comment]
I tested the automatic disabling of OMXPlayer, and found out that it works, but it doesn't re-enable OMXPlayer after playback.

**Comment by CastagnaIT** [comment]
yes is not reenabled, it's not a reliable thing to restore him

after the modification, there is no way to know whether playback has not started or has not been successful, also when exchanging video with upnext may cause side effects

Sidenote:
A dev LE told me now that on Kodi19 omx player was removed
issue: https://github.com/CastagnaIT/plugin.video.netflix/issues/500
so i have also to limit it to kodi18 to prevent errors

**Comment by dagwieers** [comment]
@CastagnaIT I understand, don't worry.

**Comment by WeaveStudios** [comment]
Hi, I arrived here because I had a problem with up next add-on. I understand it's being re written so maybe there's still a problem. Everything works as expected, but the option to enable the add-on after install it remains grayed out, despite it's installed and enabled. BTW, I can go to up next settings without problem.

**Pull request merged**
