### PR TITLE
Device uuid

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

It is no longer possible to use MAC-address to make safe the credentials
due to security-related changes in operating systems in first place android 9 and up
So change keys to use a per device UUID

<s>Side note for macos:
in _get_macos_uuid
the os.popen should be replaced with subprocess
however, first we need to find a user that have an apple products to run the tests
</s>

### CODE REVIEW

**Comment by CastagnaIT** [comment]
This is only for test purpose,
- on windows works

- on kubunu-linux works, need to be tested like omsc

- on MacOs/Iphone or tablets
Need to be tested,
according to the information on the net the system should work
but we need someone to provide the logs for a test

- on android
@smeulf you know the situations,
I added kernel info platform as i wrote to you from python platform module,
so the "System.OSVersionInfo" from kodi is too slow it does not get the information immediately
often return a "Busy" text string

i checked your points:
- the timezone (+3 -1 -2 etc..), i have tryied to use the tzlocal module included in kodi python but i couldn't get it to work do not recognize the module
(I would like to avoid overloading the app by adding manually other modules)

- System name? you mean "windows", "linux" etc...does not seem very suitable
- Language, i have the feeling that it is not reliable get it by a python module inside kodi
- have bytes instead of megabytes, at the moment i didn't look for other ways

**Comment by Smeulf** [comment]
By system name I ment 'computer name'.

I agree if some data can't be retrieved correctly, then they should be excluded from UUID creation.

I gonna run some tests under:
- Windows 10 home x64
- Windows 10 pro x64
- I'll setup a Windows 10 x86 in a VM for a try too

- LibreELEC for RPi
- LibreELEC for x86/x64 (VM only)
- OSMC for RPi

We definitely need Android tests and MacOS. Those are the most affected by the bug, we may find some willing people :)

Can you offuscate the UUID in logs? Like keeping only the 5/10 first chars and put some stars for the remaining ones?

**Comment by CastagnaIT** [comment]
yes when i implement it for credentials i will eliminate **all** debugging output
to now it is necessary to verify that it is always same string
in the case find out how to get something more on android let me know

**Comment by CastagnaIT** [comment]
I need someone who gives me availability to make a test
**ONLY ON: APPLE devices like Macintosh and/or iphone and/or tablet**

**IMPORTANT!**
SEND THE LOG FILE OR LINK IN PRIVATE FORM TO MY E-MAIL ADDRESS (first page of my github),
THE LOG CONTAINS PRIVATE INFORMATION OF THE DEVICE USED
THAT IS BETTER DO NOT MAKE THEM PUBLIC.

The test allows me to understand if i can get an ID of the device to encrypt your credentials,
i need to have TWO logs: one after opening the netflix addon, another one after one reboot of devices in the same way.
Remember to enable kodi debug info
[plugin.video.netflix_TEST2.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3586551/plugin.video.netflix_TEST2.zip)

**Comment by Smeulf** [comment]
Not sure what data it can retrieve:
https://android.googlesource.com/platform/development/+/master/python-packages/adb/device.py

**Comment by Smeulf** [comment]
Also still thinking.
We need a way to ask for credentials again in case they can't be decrypted, at least one time, to ensure migration from previous encryption to new encryption.

I was thinking about a flag in the db like 'enc_version' = 2, so if it's not 2 then ask for credentials. But it may be wise to just handle the exception a wrong encryption key generates. I don't know what's the best way...

**Comment by CastagnaIT** [comment]
> Not sure what data it can retrieve:
> https://android.googlesource.com/platform/development/+/master/python-packages/adb/device.py

nothing of useful it can be used only from "outside" of the android device

**Comment by CastagnaIT** [comment]
a user who performed the macintosh test contacted me, unfortunately the code didn't work
i tryied to change the string to use subprocess:
`uuid_value = subprocess.check_output("/usr/sbin/system_profiler SPHardwareDataType | awk '/UUID/ { print $3; }'")`
but the command going in error without an output message
it's a little difficult to do tests without a device by hand
first of all because i don't know mac os x...and this user is not expert i can't ask for particular things

I have tried several attempts to install macosx in virtualbox to have a chance to make tests
but without success... when start machine black screen or stuck at efi boot install

**Comment by Smeulf** [comment]
@Thunderbird2086 had the problem on Mac (see https://github.com/CastagnaIT/plugin.video.netflix/issues/186), maybe he would be experimented enough to help?

**Comment by CastagnaIT** [comment]
i have found this
https://github.com/filipp/system_profiler/blob/master/system_profiler.py
should be useful to get something working, so i hope..

**Comment by Smeulf** [comment]
https://github.com/CastagnaIT/plugin.video.netflix/pull/192#issuecomment-529096487 updated regarding my current tests. Take a look from time to time, i'll keep update it.

**Comment by Smeulf** [comment]
Do you need more linux version tests?
Mint, Ubuntu, Debian? Any other?
It takes sometime to download the ISOs but it's not a problem to try tomorrow or monday (on VM only)

**Comment by CastagnaIT** [comment]
Mmh no other distributions should be use the same id path
On omsc and librelec its OK?

**Comment by Smeulf** [comment]
> On omsc and librelec its OK?

Both rebooted to confirm, all fine, UUIDs are generated and same after reboot.

I figured out you didn't change the encryption method yet hahaha

**Comment by Smeulf** [comment]
Windows 10 x86 works fine too.

**Comment by CastagnaIT** [comment]
as long ago microsoft said "why change a thing if it works"...
but lately it sounds strange!?🤣

I did a last test with mac following about the operations of the link I posted
and has WORKED! has extracted hardware information from the mac

now I have to figure out how to extract the right information

**Comment by CastagnaIT** [comment]
on my honor8 android is working, but as previously mentioned, every time the operating system is updated, credentials will be requested...and the strings are not very robust
the current system in android is not perfect but I cannot find other solutions that can be used
also in the latest versions of android they have denied access to all types of serials

yesterday i have found "pyjnius" to get access to android class (ANDROID_ID), but also this module have part of C... again nothing.

**Comment by CastagnaIT** [comment]
i have found the hostname in android
i need you can check in your andorid 9 if there is the property
you can in this way:
install app Material Terminal
After opened write: getprop | grep hostname

should be output the hostname string
let me know

**Comment by CastagnaIT** [comment]
ok tested on an HonorPlay with android 9 it's working
now i want understand if the hash contained in hostname is always the same
i asked help to xda i'm waiting a reply

**Comment by Smeulf** [comment]
> After opened write: getprop | grep hostname:

[net.hostname]: [HUAWEI_P10-38382af9f94208]

Looks interesting!

**Comment by CastagnaIT** [comment]
...bad news
https://android.googlesource.com/platform/frameworks/base/+/fc1b6a3f2abbcea391001165df2357c9b7397bbf%5E%21/
property deleted on android 10

**Comment by Smeulf** [comment]
They're trying to make us crazy?!

**Comment by CastagnaIT** [comment]
that's enough for me, can you do a quick check?

**Comment by Smeulf** [comment]
That's working, tested setting the other device first as main, the update refused to work as expected. Then set the device as main, "et voilà".

However, sometimes _compute_next_schedule shows `'Library auto update scheduled is disabled'` as if it has no sufficient time to retreive `g.ADDON.getSettingInt('auto_update')`

Maybe we should add a `xbmc.sleep(2000)` to make sure the setting is correctly written on the file before getting it.

**Comment by CastagnaIT** [comment]
you can test with minor time like 500?
so add an argument to 
_compute_next_schedule(delay=False)
and use it only with onSettingsChanged

**Comment by fateddy3496** [comment]
Hi guys. I can test android 9 and 8.1 which also didn't work. Let me know what I can help with. I'm a coder from the OLD days with a bit of time on my hands these days. Also can test windows of course.

Cheers

**Comment by Smeulf** [comment]
@CastagnaIT 500ms is indeed sufficient.

See associated PR https://github.com/CastagnaIT/plugin.video.netflix/pull/202, I did it the brutal way again haha

**Comment by CastagnaIT** [comment]
@dagwieers
can you understand why winreg is not imported correctly?

**Comment by dagwieers** [comment]
Because it is not a Windows system ?

**Comment by CastagnaIT** [comment]
also adding `sys.platform.startswith('win')` not work

**Comment by CastagnaIT** [comment]
I don't understand why, the code works correctly we have already tested on all types of systems

**Comment by dagwieers** [comment]
pylint does code analysis based on what is available on the system. If you call modules, classes and methods, it verifies if they exist and are called correctly, without running the code. So it cannot evaluate expressions and doesn't know what parts of the code are dead for a specific platform.

So in that case you have to exclude pylint checks. It is a trade-off.

**Comment by CastagnaIT** [comment]
exactly i had to disable some checks

**Pull request merged**
