### PR TITLE
Update Spanish Translation [es_ES]

### PR DESCRIPTION
**Pull request by roliverosc**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Translation

### CODE REVIEW

**Comment by roliverosc** [comment]
@boblo1

**Comment by boblo1** [comment]
> @boblo1

We need to start a discussion about the term used for 'library'. I think it's better to perform a global replace for the term 'biblioteca' to be replaced with 'colección'. Why? Because 'colección' is the term used in the spanish translation of Kodi. Both terms are correct , but that way our translation would be more integrated with the main application. I did this in my last revision, but @CastagnaIT refused to commit the change without your participation. Here is my attempt for your message string:
'Incluir **colección** de Kodi (sólo enviando datos)'

**Comment by roliverosc** [comment]
Hi @boblo1. You are right some skin are introducing "colección" as library translation but then how would we translate a collection of movies also as a "colección".  For me the Library should continue to be translated as a "Biblioteca" to differentiate it from a film collection or movie set.

**Comment by boblo1** [comment]
> how would we translate a collection of movies also as a "colección". For me the Library should continue to be translated as a "Biblioteca" to differentiate it from a film collection or movie set.

The term 'collection' does not appear in current translation of the Netflix add-on (@CastagnaIT did not use it), so this is not an issue and you can perform that global replace (biblioteca -> colección). I still think it is better to use this term to get a more integrated translation. Since we cannot change the core translation, it's better to adapt ours.

> In my opinion it is not well translated.
Yes, it is. 'Library' has several meanings:
1. Biblioteca
2. Colección
3. Discoteca (colección de discos)
4. Videoteca
See this: [https://www.wordreference.com/es/translation.asp?tranword=library](url)

> The translation of "movie sets" as "saga" is not correct for me. In Spain "saga" is not widely used.
Generally a 'movie set' is a 'plató (de cine) ' in english. But you have to understand the context here. Here a 'movie set' refers to a 'conjunto de películas'. According to Wikipedia, you can generally use the term 'saga'. See this: [https://es.wikipedia.org/wiki/Serie_cinematogr%C3%A1fica](url) (2 or more films part of a set sharing same story and characters). So it is correct in this context.

> PD: Did I change the spanish translation kodi core? I have no time.

**Comment by roliverosc** [comment]
I have permission of the kodi team to do it i am member of translation team.

**Comment by roliverosc** [comment]
I close the pull request. Create your pull request for spanish translation.

**Comment by boblo1** [comment]
> I have permission of the kodi team to do it i am member of translation team.
> 
> I close the pull request. Create your pull request for spanish translation.
> 
> https://www.transifex.com/teamxbmc/kodi-main/glossary/es_ES/?filter=Library&count=25

I don't have permission to view the link.

On the other hand, as you have permission to make changes, please replace the term '**suspenso**' with '**suspense**' (movie genre) in the language file of Kodi (library). I think it is a bad translation, probably made by South American people. Thanks in advance.

**Comment by roliverosc** [comment]
https://i.imgur.com/CTzMDgf.jpg

**Comment by roliverosc** [comment]
What skin do you use? You should open a post the official forum.

**Comment by boblo1** [comment]
> What skin do you use? You should open a post the official forum.

The default, Estuary. I thought you could make that change yourself. Thanks anyway.

**Comment by roliverosc** [comment]
I can do it but there are skins that contemplate their own genres.

**Pull request closed without merging**
