### PR TITLE
Version bump (0.15.3)

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Version bump

### CODE REVIEW

**Comment by Smeulf** [comment]
Can you hold the PR until tomorrow? I'd like to check something regarding MySQL and utf-8. Thanks.

**Comment by CastagnaIT** [comment]
yes not merge now, this PR is as notice

**Comment by dagwieers** [comment]
Also, after release we should probably bump the release again to `0.15.3.git`, so there is a clear distinction between development code and the real release.

What I find confusing is that the Changelog mentions `15.3`, whereas the actual version is `0.15.3`

**Comment by CastagnaIT** [comment]
do you mean in the comment of the commit?
the previous developer usually wrote this way,i just continued on his way, but i can add the missing "0." is not a problem

**Comment by CastagnaIT** [comment]
@Smeulf Let me know if current master branch is ready

**Comment by Smeulf** [comment]
The master branch looks fine. I've been testing the credfix branch since more than a week without any problem, and validated my commits, so all green, but the changelog where you may remove "-Initial conversion to python 3".

I'll tests the Python3 branch ASAP.

**Comment by Smeulf** [comment]
Well it's working, more or less. I mean in general there's no error.

But I miss a lot of items in My List, it now shows only 48 items instead of 74.
My wife profile has 48 items instead of 58.

Strange that I get 48 for both profiles. Is there a call not made for the rest of the list maybe?

If I browse "All movies", then select a genre, I just get 50 items, instead of 100. And no more "Next page"

It stopped working at this commit https://github.com/CastagnaIT/plugin.video.netflix/commit/bf109727e1f253b0fea1484f3f6280fb11e1be26

At the previous one, it works https://github.com/CastagnaIT/plugin.video.netflix/tree/6b4b30479fa0a7329b57d07759aa32fc31cb0dd2

Here's the log if it can help: https://paste.kodi.tv/guquwiliyi.kodi

**Comment by Smeulf** [comment]
Things I can't test right now, and potentially changed by the same commit:

- Forced subtitles workaround (you know how to check it better than me)
- Import old library format to new database (I don't have any old files anymore)

**Comment by Smeulf** [comment]
The issue is in nfsession.py, perpetual_path_request()

I reverted locally the changes introduced there and it works fine again. Didn't analyse why yet. I bet you'll be faster than me ;)

**Comment by Smeulf** [comment]
Fix: https://github.com/CastagnaIT/plugin.video.netflix/pull/217 
Just a superfluous break instruction.

**Comment by dagwieers** [comment]
By reviewing #194 (because of #217) I found another issue (#218).
I don't know what the effect is of this issue, but it wasn't working as before (as it should).
Sorry for that :-/

**Comment by Smeulf** [comment]
A new potential issue in master: https://github.com/CastagnaIT/plugin.video.netflix/issues/186#issuecomment-532759501

**Comment by Smeulf** [comment]
Also, can we merge https://github.com/CastagnaIT/plugin.video.netflix/pull/208 and https://github.com/CastagnaIT/plugin.video.netflix/pull/206 before bumping?

**Comment by CastagnaIT** [comment]
in #208 it seems to me that changes were made in the language en but they have not been reported in other languages

**Pull request merged**
