### PR TITLE
Update & repair polish translation

### PR DESCRIPTION
**Pull request by notoco**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Please add also the new lastest ids

**Comment by CastagnaIT** [comment]
please study git shell 😢

**Comment by notoco** [comment]
Yes, I know - I still have a problem with that.
I'm not that friendly with it - I use "Github Desktop" and I have an eternal problem with the same ... I promise to improve.
So what, close this and add a new correct one?

**Comment by CastagnaIT** [comment]
not close so attach here in the comment the right file and i provide to commit

**Comment by CastagnaIT** [comment]
done

**Pull request closed without merging**
