### PR TITLE
Delegate upnext to start the next video

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### Description

as title
Ref. https://github.com/im85288/service.upnext/pull/133

Sidenote: makes the transition between video smooth and fast

### CODE REVIEW

**Comment by notoco** [comment]
Very very fast - great job!

**Comment by dagwieers** [comment]
This should work now with Up Next master branch and the upcoming v1.1.0 release !

**Comment by CastagnaIT** [comment]
I'll wait till it comes out thanks

**Comment by dagwieers** [comment]
Don't wait to test it though ;-)

**Comment by notoco** [comment]
Is there a chance that it will come to the next update? works great on coreelec with the library

**Comment by CastagnaIT** [comment]
This is a breaking change, i can't join it before new upnext version is released and updated by users

I waited until today hoping that the new upnext version would be released
but it hasn't been approved yet and i don't know when it will be

i need to release the new nf version now, because there's a critical error that freeze the addon when the library sync is used
will be for the next version

**Comment by dagwieers** [comment]
As soon as Up Next v1.1.0 is approved, you are good to go.
https://github.com/xbmc/repo-scripts/pull/1276

**Comment by dagwieers** [comment]
Up Next v1.1.0 has been released.

**Comment by dagwieers** [comment]
Maybe we need to add a strict dependency to Up Next v1.1.0 in addon.xml.

**Comment by CastagnaIT** [comment]
can be added as optional? Because don't want add it as a mandatory requirement

**Comment by dagwieers** [comment]
That is indeed a possibility. For the VRT NU add-on we actually have an Integration tab in the settings, where you have an entry to install Up Next and YouTube add-ons. Once installed, the settings turn into and enable/disable integration switch and a link to the setting for each.

https://github.com/pietje666/plugin.video.vrt.nu/issues/548
https://github.com/pietje666/plugin.video.vrt.nu/pull/552

**Comment by CastagnaIT** [comment]
I can add that

**Pull request merged**
