### PR TITLE
Fix timestamp sent in event status updates

### PR DESCRIPTION
**Pull request by wagnerch**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

In profile / account / viewing activity when using "Playback > Synchronize the watched status of the videos with Netfllix" the dates are in the future by almost a full month.  My guess is Netflix probably has an upper limit on how much clock skew they will accept from the client and they just truncate it at a certain point.

Based on debugging with the Netflix Player in Firefox it is apparent that timestamps are in milliseconds since Unix time epoch.  But we are sending the value 10x greater since time.time() returns Unix time + fractional seconds, so the factor should be 1000.

I suspect there are a few other areas where timestamps may be incorrect, but they don't seem to have any negative effect.

### Screenshots (if appropriate):

Capture

### CODE REVIEW

**Comment by wagnerch** [comment]
Here is a screenshot after the fix applied:

Capture

**Comment by wagnerch** [comment]
This was the other timestamp problem I noticed, client_utc is being sent with fractional seconds but in my debugging it is just a whole number.

**Comment by CastagnaIT** [comment]
thanks to this little thing of time() output format type, i never noticed

**Comment by CastagnaIT** [comment]
I don't know if this has happened since your fix
but i see today that ContinueWatching list is now working, so is updated correctly
after played a episode of a tvshow never watched, the tvshow is now added to ContinueWatching list

steps:
1) add to my list a new tv show never watched 
2) reproduce episode 1
3) wait at least 2 minuts elapsed of video lenght and stop video
4) wait addon send the 2 refresh requests about 2/10sec depends on system speed (see log)
5) open nf website scroll to Continue watching list

very well!😎

**Comment by wagnerch** [comment]
Ahh, yeah I was wondering where that came from.  :)   That's awesome.

**Pull request merged**
