### PR TITLE
Fix multiple errors in LibraryUpdateService

### PR DESCRIPTION
**Pull request by Smeulf**
- At service very first run, settings.xml is not created yet and throws an error
"update_frequency = g.ADDON.getSettingInt('auto_update') TypeError: Invalid setting type"

- Fix ERROR: [plugin.video.netflix (0)] SQLite error no such table: app_config

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
tomorrow I'll check second commit

**Comment by Smeulf** [comment]
When using Sqlite, base class uses 'app_config' by default for get or set value, so it needs to be overwritten.

Or we can override the methods get and set value in db_shared.

I choose the easiest way.

**Comment by CastagnaIT** [comment]
you choose that brutal way hahaha
it was enough to copy the methods i have forgotten

**Comment by CastagnaIT** [comment]
first commit picked

**Comment by Smeulf** [comment]
Me? Beeing brutal? Never haha!!

**Pull request closed without merging**
