### PR TITLE
el_GR strings.po for 1.7.1

### PR DESCRIPTION
**Pull request by Twilight0**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [ ] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
Translation enhancement for version 1.7.0+

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Do you want that i merge this now or i wait merge for changes in next release?

**Comment by Twilight0** [comment]
> Please update also "Addon Disclaimer"

Sure, I will.

> Do you want that i merge this now or i wait merge for changes in next release?

Yes, unless you have to make changes in strings, I will pull those and apply to a new commit.

**Comment by CastagnaIT** [comment]
now you can rebase with last changes

**Comment by Twilight0** [comment]
Thank you, will do in a few moments.

**Comment by Twilight0** [comment]
Should be ok now

**Pull request merged**
