### PR TITLE
Video progress and watched status with Netflix services

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

With this PR begins experimentation to communicate information about the progress and watched status to the Netflix service in a two way communication.

**This PR will add this functionality only for videos running within the addon, then not from Kodi library**, for the management of progress status in the Kodi library will be done on another PR

NO ETA - NO QUESTIONS THAT ARE NOT HELPFUL

Anyone with additional information to help developing with service is welcome to

~**Highly experimental** branch, all can change frequently and completely, as needed~

1. PHASE: Implement a first version of event data system [DONE]
2. PHASE: Try to send progress state to nf service [DONE]
3. PHASE: Optimize event data system [DONE]
4. PHASE: Try to get the progress state from nf [DONE]
5. PHASE: Implement start video from an previous existing time position [DONE]
6. PHASE: Override Kodi watched status integration and implement all this as optional setting [DONE]

_Started tests before release it_

~I'm not sure that the work will be finished and i'm not able to say if it will be successful,
but to now finally i got a starting point on which to perform tests~

Discussion issue: https://github.com/CastagnaIT/plugin.video.netflix/issues/80

Current limitations:
- Works only with main profile (solution found! read below)
- The continue watching list will not be updated

How works (Wiki added):
- By default this feature is disabled, can be enabled on:
Settings->Playback->Send/Receive progress and watched status of the videos
- When enabled _all previous watched status and progress will be replaced_ by those on the website (until you disable the option)
- When you start a video playback, the "resume" feature will be updated only after watching at least the first minute of the video.
- The synchronization from Kodi to the Netflix service is immediate
- When the videos progress are changed by other devices and Kodi at the same time, in Kodi you may not see immediately the changes made by other devices. To see immediately the changes you need to _purge cache_ (or reboot Kodi).

Unresolved problems:

I FINALLY FOUND THE SOLUTION!🎉🎉🎉🎊🎊
Exists a MSL switch! and with the latest changes made it worked!
I was able to use it and communicate the data and make data requests from the right profiles!
but it is quite complicated to implement it... i think there will be a need to unify MSL and nfsession, as i suspected in the past, and this solves all the problems mentioned below!!! (except for continue watching)

will be implemented in the future with other PR because it requires different work

<pre>
The first tests were a success, only problem is the communication of MSL data in to the right profile, currently all data is sent only to the main profile

I tried these tests but failed:
-sending manifest/license requests through the nfsession does not solve the problem
-After added commit to get the "lhpuuidh-browse" cookies the situation is not changed

this problem is the same one involving other problems:
-missing audio/subtitle language on other profiles with different language set
-playing videos from a Kid profile, not give age error, this because the manifest request is always done from the main profile, then "every play" is from the main profile
</pre>

The continue watching list is not updated, i tried to implement `refreshListByContext` and `refreshVideoCurrentPositions` but they do not perform the desired effect...

### CODE REVIEW

**Comment by Badsheep** [comment]
Hello,

As a big fan of your work, as soon as I saw you updated the readme file, I downloaded this version and tried it :)
Seems nice, but doesn't seems to work completely : 

If I start a new movie in Kodi (and wait 1 minute as you explain)
When I go on the Netflix website, search that movie, it proposes me to resume it, at the point I stopped >> victory !!
BUT... the movie doesn't appear in my "Continue watching with ..." list.
Is it normal ?
That would be so great (and necessary I think)...

Once again, thanks for your great job !
Matthieu

**Comment by CastagnaIT** [comment]
I've updated the readme, but it doesn't mean that the changes are finished, i'm waiting for answers for changes in Kodi to figure out how to proceed

have you tried running "purge cache" before opening continuous watching?

**Comment by Badsheep** [comment]
Hello,

Yeah I was to impatient :)

I just tried ("purge in-memory and on disk cache")

Same result

**Comment by CastagnaIT** [comment]
true is not updated even in the website
i will try investigate thanks

**Pull request merged**
