### PR TITLE
Impl. of auto select of the last partial watched or next episode to be watched

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

A hacky implementation to auto select the next episode to watch without scroll manually every time
Kodi not offer this feature... this is better than nothing...

### CODE REVIEW

**Comment by dagwieers** [comment]
Will this fix the problem that if you watch Netflix with Up Next, that after you watch 3 episodes the virtual directory listing has the cursor on the first episode, and all episodes are marked as unseen?

Because that is what we see today in Leia after watching multiple episodes (or IIRC even after watching one episode).

**Comment by CastagnaIT** [comment]
i do not think, I had investigated and tried different ways to circumvent the problem
but the problem remains,
it seems to be a concurrence issue of gui update in kodi core

Also the "resume" a video does not work well, and i think it's another similar problem
resume time data is sent correctly, but at some point in Kodi source code the data is inexplicably deleted by a function intersected with the database (I already opened an issue but at today ignored)

**Comment by dagwieers** [comment]
We have had similar issues which we worked around in two ways IIRC
- Ensure all code paths that update metadata are very fast (make slow stuff like online updates asynchronous)
- Force our own container refresh when it is needed

This way we managed to get resuming a video working directly after you stopped playback.

**Comment by CastagnaIT** [comment]
> Ensure all code paths that update metadata are very fast

I don't think i know exactly what you mean, but the resumeTime of each listitem are already updated in realtime (in database, then when kodi require to update the episode list in GUI the values are already ready)

> Force our own container refresh when it is needed

there is a way to know when kodi refresh the list?
would make it ugly to see double refreshed

> This way we managed to get resuming a video working directly after you stopped playback.

in my case the problem of resume happens not only (in the exact moment) when you make a stop
but also if you close/reboot kodi and after reopen it you try to resume the same item,
kodi ask you to resume the video from previous time, but after dialog confermation it starts from beginning... 

and the problem is not always consistent, sometimes in a listitem the resume works, another times happen that same listitem fails to resume, that's why i opened up the issue: https://github.com/xbmc/xbmc/issues/17426

time ago i have tried to debug kodi core, and i found where in source code the resumeTime value is lost (see "Possible Fix")
Unfortunately, without more help, I'm not able to go more deeper in the code

**Comment by dagwieers** [comment]
@CastagnaIT 
>> Ensure all code paths that update metadata are very fast

> I don't think i know exactly what you mean, but the resumeTime of each listitem are already updated in realtime (in nf database, then when kodi require to update the episode list in GUI the values are already ready)

I don't know if this is technically correct, but if playback stops it takes an amount of time for Kodi to return back to the menu. If your metadata is updated before this has happened, the listing has all the updates you have made. Since setting resumetime is done in a Player thread (recommended), it means you have to do this as fast as possible, that is why we opted for asynchronous update. So we optimized that path.

>> Force our own container refresh when it is needed

> there is a way to know when kodi refresh the list?
> would make it ugly to see double refreshed

Well, if you refresh before returning to the listing, your refresh will not be acted on. So if you have a fast path to update resumetime, you can always order a refresh. If the listing was already shown, there will be a noticable refresh, but in our opinion it is better to make it functionally work right always, than avoid a visible refresh.

>> This way we managed to get resuming a video working directly after you stopped playback.

> in my case the problem of resume happens not only (in the exact moment) when you make a stop
but also if you close/reboot kodi and after reopen it you try to resume the same item,
kodi ask you to resume the video from previous time, but after dialog confermation it starts from beginning...

IIRC We update resumetime on start, pause, stop, playbackerror. We do not update resumetime (online) every X seconds, but I guess we could do this asynchronously as well.

Our biggest problem is keeping the local metadata in sync with the online metadata. If that would be possible we would not have to force the (cached) remote resumetime, but we could update the resumetime in the local metadata. @mediaminister fixed this in xbmc/xbmc#17202 , but this was not backported to Leia, unfortunately.

BTW We track all our Kodi/IA issues and feature requests at: 
- https://github.com/orgs/add-ons/projects/3
- https://github.com/orgs/add-ons/projects/4

**Comment by CastagnaIT** [comment]
oooh i think we are talking about two different things!!!... LOL

> Updating the resumetime for us means: updating our own local cache and updating the remote VOD service.

I try to explain myself better in my shitting english, i hope now you understand better

Due to particularity of netflix i preferred to use a different way, so exclude the standard kodi functionality of the watched system, by set to each ListItem these properties e.g.:

ListItem.TotalTime = the full time
ListItem.ResumeTime = some time elapsed (partial watched)
ListItem.setInfo('video', {'PlayCount': '1'}) << this only when a video is full watched

when i talk about resume time i mean the ListItem.ResumeTime

using this everything works well without use the jsonrpc override, because i set these properties,
but kodi has a bug in ListItem.ResumeTime property that lose the value when it elaborate internally the value...

---

In nf addon the resumetime value update works similary of you explaing:
when a video is played:
-in local the resumetime value is saved in realtime in a temporary cache
-in real nf server the resume time value will be send the update in async way, every minute (netflix design not an personal choice)

**Comment by dagwieers** [comment]
Ok, we came to an almost identical implementation :-)

**Pull request merged**
