### PR TITLE
KeyError: u'lists' since speedup

### PR DESCRIPTION
**Pull request by lekma**
should fix commit https://github.com/CastagnaIT/plugin.video.netflix/commit/861ec2621ca6902339fe7bce2ed1baff533d4886

### CODE REVIEW

**Comment by Smeulf** [comment]
I had that error yesterday too, but I wiped it after cleaning disk and memory cache and reboot.

Of course, I'm not saying you're fix is not needed, and that the error can't comes up again here, just sharing ;)

**Comment by lekma** [comment]
still reproducible on a clean install

**Comment by CastagnaIT** [comment]
this fix is wrong request_context_name there is no inside of lolomo list, i kept it separate for a reason, because the calls on the queries are different

show me the log with the error

**Comment by lekma** [comment]
```
2019-05-07 20:19:59.486 T:140295284823808   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 90, in <module>
                                                route(filter(None, g.PATH.split('/')))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 49, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 77, in route
                                                g.REQUEST_PARAMS)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/__init__.py", line 21, in execute
                                                executor(pathitems=pathitems)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 87, in video_list_sorted
                                                menu_data, pathitems)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 28, in set_custom_viewmode
                                                override_partial_setting_id = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 202, in build_video_listing
                                                in video_list.videos.iteritems()]
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 237, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/listings.py", line 241, in _create_video_item
                                                list_item.addContextMenuItems(generate_context_menu_items(videoid))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/kodi/context_menu.py", line 52, in generate_context_menu_items
                                                if videoid.value in api.mylist_items()
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/cache.py", line 84, in wrapper
                                                output = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 255, in mylist_items
                                                g.MAIN_MENU_ITEMS['myList']['lolomo_contexts'][0])).videos.iteritems()
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/api/shakti.py", line 243, in custom_video_list_basicinfo
                                                return VideoList(common.make_call('perpetual_path_request', callargs))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/api/data_types.py", line 70, in __init__
                                                else next(self.data['lists'].iterkeys())))
                                            KeyError: u'lists'
2019-05-07 20:20:14.182 T:140298071751040 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2019-05-07 20:20:14.350 T:140296729597696 WARNING: Previous line repeats 19 times.
2019-05-07 20:20:14.350 T:140296729597696   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/video_list_sorted/newRelease/newRelease/
2019-05-07 20:20:14.365 T:140298071751040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/directory/video_list_sorted/newRelease/newRelease/) failed
```

**Comment by CastagnaIT** [comment]
Please reproduce the error with this version and copy the entire log file with debug
[plugin.video.netflix_Test.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3154082/plugin.video.netflix_Test.zip)

**Comment by lekma** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3154123/kodi.log)

**Comment by CastagnaIT** [comment]
when you took the test, did you have "my list" empty?

**Comment by lekma** [comment]
yes 'My List' is empty

**Comment by lekma** [comment]
...but the error happens on all folders

**Comment by CastagnaIT** [comment]
I understand the problem, it is normal that it to occur on each menu
I will find a suitable solution nothing really dangerous

**Comment by CastagnaIT** [comment]
Fixed thanks

**Comment by Smeulf** [comment]
@CastagnaIT it seems not totally fixed.
I tried yesterday to upgrade from 0.14.1 to the last commit, and had the error.m again.

Had no time to get a correct log, I will provide it when I'm back home on monday.

**Comment by CastagnaIT** [comment]
strange okay I'll wait for the file, go quietly, you don't have to hurry

**Comment by Smeulf** [comment]
Well, on a fresh install, I can't reproduce the problem anymore.

I installed a previous version (before list loading speedup) then the last commit avaliable, and no problem :/ I hate random errors, and I wonder if it can be related to the service once again (nothing exported on the fresh install).

If you agree, we'll see when you'll release it, and as a workaround we can still tell people to clean cache and restart... On my main system, the error did not pop up again anyway since the update.

**Pull request closed without merging**
