### PR TITLE
Use f-strings where it makes sense

### PR DESCRIPTION
**Pull request by johachi**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [ ] I have successfully tested my changes locally (ran the linter and was going to run the others before opening this PR, but then I accidentally pressed the wrong button before running everything. Sorry about that 🙇 )

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which changes behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactor (non-breaking performance or readability improvements)

#### Use f-strings instead of `.format` and string concatenation

I was going to look into a problem regarding profile name not displaying correctly, but when looking at the code base I saw a lot of strings that use the old `.format()` injection of variables instead of `f-strings`. I feel that `f-strings` are (in almost all cases) easier to read than the old (and slower) `.format()` syntax.

```python
# Example 1:
LOG.debug('Registered AddonSignals slot {} to {}'.format(name, callback))
↓
LOG.debug(f'Registered AddonSignals slot {name} to {callback}')


# Example 2:
query = 'SELECT {} FROM {} WHERE {} = ?'.format(table_columns[1],
                                                table_name,
                                                table_columns[0])
↓
query = f'SELECT {table_columns[1]} FROM {table_name} WHERE {table_columns[0]} = ?'
```

I did update almost all places that used `.format()`, but  I did keep it in a few places where I thought that it was easier to read than `f-strings`.

I did also update a lot of string concatenation to be f-strings instead, but did here also keep the string concatenation at a few places where I thought it made sense.

```python
# Example 3:
query = 'SELECT ' + enum_vid_prop + ' FROM video_lib_tvshows WHERE TvShowID = ?'
↓
query = f'SELECT {enum_vid_prop} FROM video_lib_tvshows WHERE TvShowID = ?'


# Example 4:
sets_columns = ['@' + col for col in columns]
↓
sets_columns = [f'@{col}' for col in columns]


# Example 5:
data += '\nDebug enabled: ' + str(LOG.is_enabled)
↓
data += f'\nDebug enabled: {LOG.is_enabled}'
```

I thought that "this can't be too much work, let's just do it", and totally regretted it because it took a lot of time 😆 But I understand if not everyone likes `f-strings` (even though I love them), so totally fine if you want to not accept it due to "not matching coding style". Anyhow, still hope you like it 🤞 

#### Reformat if-statement

https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/97cda96e499aea066645d2fcb7aead7f5c96db6a

#### Grammar in PR-template

(Nothing big, just my auto-correct that found them):
https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/c8f26eb9343394ec870f669b24985a2fb1ddf094

### CODE REVIEW

**Comment by CastagnaIT** [comment]
> I thought that "this can't be too much work, let's just do it", and totally regretted it because it took a lot of time

hehe yes i know... 
that's why that some parts of the code have been unchanged for time
update everything take time to be maintained...

I appreciate your refactor which is only now possible as I have recently adopted the python 3.6 as miminum requirement

there are only few thing that i prefer change:

* LOG.xxx() methods

some of these are not updated to the "new" logger methods, that's why there is still the "format",
then please remove the f-string and use the method arguments,
this to lighten the load on the CPU, when the logger is disabled,
then from your example above will become:
```
# Example 1:
LOG.debug('Registered AddonSignals slot {} to {}'.format(name, callback))
↓
LOG.debug('Registered AddonSignals slot {} to {}', name, callback)
```
then the "format" is done by the logger code only if needed

* resources/lib/services/nfsession/session/access.py 

on your change for this special case i prefer keep the .format style

everything else i think is fine thanks

**Comment by johachi** [comment]
Hi @CastagnaIT , thank you for your quick review.

>     * resources/lib/services/nfsession/session/access.py
> 
> 
> on your change for this special case i prefer keep the .format style

Sure, done here: https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/066911ea0525b541a8faa3ae66db63c6198e4e8a


>     * LOG.xxx() methods
> 
> 
> (...)  please remove the f-string and use the method arguments,
> this to lighten the load on the CPU, when the logger is disabled,
> then from your example above will become:

I'm unsure if you wanted this done only for `LOG.debug()` calls or if I should do it also for `LOG.error()` and `LOG.info()`?

I did all `LOG.debug()` statements here: https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/d36e531c49ff203f5a5dbcdc9e62b782afc75460. Please let me know if I should do the same for the other two log methods as well.

**Comment by CastagnaIT** [comment]
> I'm unsure if you wanted this done only for LOG.debug() calls or if I should do it also for LOG.error() and LOG.info()?

yes for all LOG methods, debug/error/info/warn

when you will have done please join the last "feedback" changes with the appropriate already existing commits

**Comment by johachi** [comment]
> > I'm unsure if you wanted this done only for LOG.debug() calls or if I should do it also for LOG.error() and LOG.info()?
> 
> yes for all LOG methods, debug/error/info/warn
> 
> when you will have done please join the "feedback" changes with the appropriate already existing commits

@CastagnaIT 

Done here and merged into earlier commit: https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/5abf3ea2f29dea7a18f7a2d6019b015223e224e5.

Also merged the latest master into the branch here: https://github.com/CastagnaIT/plugin.video.netflix/pull/1177/commits/962f09e322abdd91a6458332e679059426450806. Merge conflict was due to the LOG statement.

Please take a look :)

**Comment by CastagnaIT** [comment]
look good ok!

but i do not like to have unnecessary commits, you can join these commits:
066911ea0525b541a8faa3ae66db63c6198e4e8a
5abf3ea2f29dea7a18f7a2d6019b015223e224e5
with the first one:
3bf4f52acfc64bac730e01bc42dd02251f0247a4

and this commit there must not be:
962f09e322abdd91a6458332e679059426450806
to remove it you need to rebase your local branch with upstream master branch

**Comment by johachi** [comment]
> look good ok!
> 
> but i do not like to have unnecessary commits, you can join these commits:
> [066911e](https://github.com/CastagnaIT/plugin.video.netflix/commit/066911ea0525b541a8faa3ae66db63c6198e4e8a)
> [5abf3ea](https://github.com/CastagnaIT/plugin.video.netflix/commit/5abf3ea2f29dea7a18f7a2d6019b015223e224e5)
> with the first one:
> [3bf4f52](https://github.com/CastagnaIT/plugin.video.netflix/commit/3bf4f52acfc64bac730e01bc42dd02251f0247a4)
> 
> and this commit there must not be:
> [962f09e](https://github.com/CastagnaIT/plugin.video.netflix/commit/962f09e322abdd91a6458332e679059426450806)
> to remove it you need to rebase your local branch with upstream master branch

@CastagnaIT done and force-pushed! Sorry that I did not understand you at first. I'm so used with squash-and-merge 😅

Hope everything looks good now.

**Review by CastagnaIT — APPROVED** [review]
well done thanks for your first contrib!
i will merge your PR after the new add-on release

**Pull request merged**
