### PR TITLE
New templates

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Types of changes

Create new separated templates to:
-bug
-feature
-support
-pull request

inspired by the kodi repository and according to github explanations it is possible to create separate templates, this can simplify things for us and users

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by Smeulf** [comment]
Shall VPN policy be added?

**Comment by CastagnaIT** [comment]
in general we should follow the policy of the forum rules
but it does not seem to me the case to list every rule

however we can insert a warning at the end of the document with a link (in the form of a comment) that if someone does not respect the Kodi rules the request will be eliminated

**Comment by CastagnaIT** [comment]
so i have open a temporany test repo https://github.com/CastagnaIT/temp/issues
it's working good!
now just complete the documents

**Comment by CastagnaIT** [comment]
updated i think it's okay

**Comment by Smeulf** [comment]
Nice!

**Pull request merged**
