### PR TITLE
Little fix in PL

### PR DESCRIPTION
**Pull request by notoco**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

## Screenshots (if appropriate):

[You can erase any parts of this template not applicable to your Pull Request.]

### CODE REVIEW

**Comment by CastagnaIT** [comment]
combine the two commits to one, then do a push forced, then i'm gonna do the merge

**Comment by notoco** [comment]
If I only know how...

**Comment by CastagnaIT** [comment]
just delete the commits you made on your branch, then make the change again by creating a new commit. Then do a git push -f ...
if you use git, you should know the basics otherwise don't create pull requests, rather send me the modified file

**Comment by CastagnaIT** [comment]
I'll never take all this trash, first you have to delete all previous commits...

**Comment by notoco** [comment]
I apologize for this mess. I am an amateur, not a professional. I did everything via www github, but I see that however GitKraken and the console in Linux should be my friends. I removed the fixes. I will throw a new pull request.
Sorry again

**Comment by CastagnaIT** [comment]
it's okay, we've all been newbies,
however the github app is ugly, and the site performs only very limited operations
to operate with git is done only via console

**Comment by notoco** [comment]
The best thing is that I have been using Linux for 15 years and I love the console, but unfortunately I do not get it github

**Pull request closed without merging**
