### PR TITLE
Profiles Management Improvement

### PR DESCRIPTION
**Pull request by Smeulf**
Related to https://github.com/CastagnaIT/plugin.video.netflix/issues/176
If profile_list is empty, do not delete all profiles in databases

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
to my eyes this is not correct, for what purpose?
if I change a profile or delete it, in the database all the data of profiles no longer existing will remain forever

**Comment by CastagnaIT** [comment]
profile_list it should never be empty

**Comment by Smeulf** [comment]
> should

Yes I agree. But if for any reason it is, all settings related to all profiles will be deleted in both db. It's not a big coast to check imo.

**Comment by CastagnaIT** [comment]
I preferred a lighter solution commited in my branch, this cause problems beecouse the profiles are not updated, discrepancies are created in the lists loaded

**Pull request closed without merging**
