### PR TITLE
Add extra error logging for 'locale_id' issue

### PR DESCRIPTION
**Pull request by Smeulf**
Try to determine origins for https://github.com/CastagnaIT/plugin.video.netflix/issues/78

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
I want to wait to merge this,
I'm trying a new way which could solve all the problems related to saving/reading the settings
as soon as i have something working i let you know

**Comment by Smeulf** [comment]
I propose you do the changes in a new branch so I can test it for a week or 2 before you release it.

That won't make it bug free, but it gives us a chance to eliminate the most annoying if some exists ;)

**Comment by CastagnaIT** [comment]
I haven't written all the basic code yet
if the thing is successful i'll put it as you say on a new branch
so you can discuss any changes

**Comment by Smeulf** [comment]
CLosing because of the database current work. This PR is becoming obsolete

**Pull request closed without merging**
