### PR TITLE
Migration to HTTP/2 network protocol

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

~**This is currently experimental**~

Last year the website is migrated to the HTTP/2 protocol
currently the web session is managed by the Requests module which does not support HTTP/2

This PR introduces the use of the HTTPX module, although the HTTP/2 support is still under development in this module seems to work well.
I think that the HTTPX module is the most up-to-date HTTP/2 module of this moment.

The HTTPX package is not provided with Kodi and is unlikely to be included for our request, because this add-on has not been approved for Kodi repository, it could be added if other approved add-ons will use this module,
in the meantime, you will need to include it as internal package including all dependencies and subdependencies.

This PR provides a first solution to this future problem and i think that this PR will not be included in the master branch until the current HTTP1.1 protocol will cause other problems with the endpoints or the website discontinue the support.

**TODO List:**
- ~To check if all dependencies and sub-dependencies of each module are in place~
- ~Check cookies code~
- ~Check TCP keep-alive communications~
- ~To implement close session on addon closing~
- ~Although HTTPX imitates Requests with similar properties/arguments a quick recheck of each method is needed~
- ~Test all endpoints (currently tested: login, main menu and playback)~
- ~Test standard login on various systems to ensure no regressions (to check if "Incorrect password" error will be fixed or worsened)~
- Investigate for error: `httpx.RemoteProtocolError: <ConnectionTerminated error_code:ErrorCodes.COMPRESSION_ERROR, last_stream_id:2147483647, additional_data:485041434b202d20696c6c6567616c20696e6465>`<br/>happen only sometimes and after playing multiple videos, ATM cause not know, could be also an httpx bug (https://paste.kodi.tv/iyubevuxey) (UPD 23/06/2021 after updated all sub-deps seem there is no more errors at least on Windows)

**From my tests this PR seem to fully fix the user+password login issues,
i have tried test logging several times on Windows, Linux Mint, CoreELEC with the result of 100% login success,**
hoping it is not a coincidence it would be helpful if someone report login test feedbacks

### CODE REVIEW

**Comment by Essam312** [comment]
I tested the login in a clean installation of Kodi 19.1 with the email and password and it worked without any problem without the need for using the authentication key, I'm using windows 10.

**Comment by CastagnaIT** [comment]
good to hear!

**Comment by CastagnaIT** [comment]
hi @betatester3016 
when you will have time, can you do a test with this version?
[plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6835864/plugin.video.netflix_1.16.2%2Bmatrix.1_20210718_http2_t1.zip)

I need to know a simply thing, if the standard login (user+password) works without raise error "incorrect password",
please take attention when you write the credentials (to not invalidate results),
of course before delete previous addon versions and related data (if installed).

On systems:
- Linux desktop computer (like ubuntu etc... as you prefeer, x86)
- ARM device with LibreElec (or CoreElec)

**Comment by betatester3016** [comment]
> I need to know a simply thing, if the standard login (user+password) works without raise error "incorrect password",
> please take attention when you write the credentials (to not invalidate results),
> of course before delete previous addon versions and related data (if installed).
> 
> On systems:
> 
> * Linux desktop computer (like ubuntu etc... as you prefeer, x86)
> * ARM device with LibreElec (or CoreElec)

Sorry for the late reply: I'll look into that this evening.

**Comment by betatester3016** [comment]
@CastagnaIT Sorry for the late reply, I was of the grid for a few days. I'll look into it this evening.

**Comment by betatester3016** [comment]
@CastagnaIT 

- [x] Ubuntu 20.04.2 LTS on x86
- [x] CoreELEC 19.2 RC2 on S905X3

I confirm being able to log in with username and password on both O.S. when using: plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1

No auth key needed

**Comment by betatester3016** [comment]
@CastagnaIT 

- [x] Ubuntu 20.04.2 LTS on x86
- [x] CoreELEC 19.2 RC2 on S905X3

I confirm being able to log in with username and password on both O.S. when using: plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1

**Comment by betatester3016** [comment]
@CastagnaIT 

- [x] Ubuntu 20.04.2 LTS on x86
- [x] CoreELEC 19.2 RC2 on S905X3

I confirm being able to log in with username and password on both O.S. when using: plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1

The results can be replicated by uninstalling and reinstalling the provided add on.

**Comment by betatester3016** [comment]
@CastagnaIT 

- [x] Ubuntu 20.04.2 LTS / Kodi 19 on x86
- [x] CoreELEC 19.2 RC2 on S905X3

I confirm being able to log in with username and password on both O.S. when using: plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1

The results can be replicated by uninstalling and reinstalling the provided add on.

**Comment by CastagnaIT** [comment]
Thank you i am testing/using this version from about 1 month, and to me works good, i do not see wrong behaviours/errors
i'm thinking of merge it soon

**Comment by Ronny-nerd** [comment]
Android 9 = Nvidia Shield TV 
and plugin.video.netflix_1.16.2+matrix.1_20210718_http2_t1

No Problem with user+password login = no authentication key  = all OK

**Comment by CastagnaIT** [comment]
thanks for the report i think to include this on next release if i will find a bit of time

**Pull request merged**
