### PR TITLE
Update polish translation

### PR DESCRIPTION
**Pull request by notoco**
Update polish translation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@notoco please translate this here, so i'll put it in
"There is no contents"

**Comment by notoco** [comment]
I completely do not understand ... we do not combine commits;)

**Comment by CastagnaIT** [comment]
I just asked you to translate that sentence into your language

**Comment by CastagnaIT** [comment]
Write me the translation here

**Comment by notoco** [comment]
LOL...
Brak zawartości

**Pull request merged**
