### PR TITLE
better navigation for 'genres' and 'search' contexts based item lists

### PR DESCRIPTION
**Pull request by lekma**
@CastagnaIT please have a look, if you like it enough we might be able to extend it to the genres/search results.

Consider this pull request as a basis for discussion more than a ready to merge proposal.

thanks

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Thanks for the idea will be useful to me :) I had already thought of such a thing, but before trying to do it, I have to implement the sorting for lists, because it is possible that with the sorting of the list creates several problems

**Comment by lekma** [comment]
I really think the qol improvements these small changes bring (avoiding timeouts/getting full lists) make them worth considering for merging while you work on a fully integrated solution (especially right now that you still are in a beta phase).
Please tell me if I'm missing something.
On a side note, do you know of any [un]official documentation about netflix api enpoints and parameters?

**Comment by CastagnaIT** [comment]
for what i know, there is no really useful documentation, just vague old examples that serve no purpose

**Comment by CastagnaIT** [comment]
Thanks for the help, I had to work hard on it anyway but i was able to add it correctly, it's possible that there are bugs left i'll see the future feedback

**Comment by lekma** [comment]
well, thx, I'll give it a try

**Pull request closed without merging**
