### PR TITLE
Changes to licensed manifest request

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which changes behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactor (non-breaking performance or readability improvements)

### Description

New changes to website reveals more info,
the "Licensed manifest" request v2 provide the manifest and license data all in one

now that we no longer have to make a separate call to get the license,
ISA fails to process license data due to different DRM session
this will be fixed by https://github.com/xbmc/inputstream.adaptive/pull/873
~so it will be necessary to have that PR merged (on both versions for kodi 19/20) before proceeding with these changes~
PR merged on kodi 19/20 versions

~unfortunately this still doesn't solve the 1080P problem on linux ARM devices,
test at today 20/03/2022 no way to make it works, 
as this situation changes on its own without intervention in the add-on, IMO the problem is not on our side
in any case I have no other idea of what could be done for ARM devices~
was a problem of Nexus version of InputStreamAdaptive, now fixed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@wagnerch i do not remember anymore have you nvidia shield to make a test?
i need only check if 1080P and 4k works as usual

needs ISAdaptive patched:
Android aarch64: https://jenkins.kodi.tv/job/xbmc/job/inputstream.adaptive/job/PR-873/4/artifact/cmake/addons/build/zips/inputstream.adaptive+android-aarch64/inputstream.adaptive-20.1.2.zip

**Comment by wagnerch** [comment]
@CastagnaIT I only have an RPi4 & Vero 4k+, no NVidia Shield.  I also dropped to SD, their prices are getting too high for what they have to offer.  Still considering dropping the service completely.

**Comment by CastagnaIT** [comment]
i understand you, the prices start to be too higher IMO for nothing... I don't see any exciting new videos in last years
if i have also dropped to HD (from 4k) and i also considering to drop to SD in the price will be increased again

**Comment by CastagnaIT** [comment]
this could compromise my support to the addon but there is no other options

**Comment by betatester3016** [comment]
I can run tests on following devices:

```
Hardkernel Odroid N2+
Khadas Vim 3
Nexbox A95X B7N
Tanix TX3 Max
Vontar X96 Mini
Turewell A95X F2
Tanix TX5 Plus
Ugoos AM7
Nvidia Shield Pro
Amazon Fire TV Stick 4K
```

The Netflix apk for Android is working fine on the Shield. So is the Netflix addon for Kodi under Kodi 19.3 for Android. I get in both cases 1920x1080p HW decoding.

If there are any specific tests you want run, let me know.

**Pull request merged**
