### PR TITLE
Reworked parental control (netflix changes)

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Due to netflix changes parental control was broken

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@tweimer @notoco 
hi last time you have tested parental control
can you do again?

use version you need:
Kodi 18 [plugin.video.netflix_1.2.2_20200508.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4601079/plugin.video.netflix_1.2.2_20200508.zip)
Kodi 19 [plugin.video.netflix_1.2.2+matrix.1_20200508.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4601080/plugin.video.netflix_1.2.2%2Bmatrix.1_20200508.zip)

**Comment by tweimer** [comment]
One issue I found so far: When you enter invalid password, you get Exception:HTTPError. There should be a better message.

**Comment by tweimer** [comment]
Also it is impossible to use that dialog with a keyboard.

**Comment by CastagnaIT** [comment]
Thanks fixed,
I think now is better

[plugin.video.netflix_1.2.2+matrix.1_20200509.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4602982/plugin.video.netflix_1.2.2%2Bmatrix.1_20200509.zip)
[plugin.video.netflix_1.2.2_20200509.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4602983/plugin.video.netflix_1.2.2_20200509.zip)

**Pull request merged**
