### PR TITLE
Modify Issue Template: NO LOGS? NO HELP!

### PR DESCRIPTION
**Pull request by Smeulf**
## Types of changes

Hopefully will fix the 'No logs" users issues... 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](Contributing.md) document.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by Smeulf** [comment]
You don't have to like it and can close it if you don't want it ;) It's just I'm getting bored with missing logs, as you are lol

**Comment by moreje** [comment]
My pro lem is that I can't find any log from my kodi on android.. Even After enabling logging option :(

**Comment by wintuxx** [comment]
You can find it:

android/data/org.xbmc.kodi/.kodi/temp

gesendet mobil

moreje <notifications@github.com> schrieb am Do., 22. Aug. 2019, 20:16:

**Comment by wintuxx** [comment]
And activate show hidden files/folder

Joerg <wintuxx@gmail.com> schrieb am Do., 22. Aug. 2019, 20:44:

**Comment by CastagnaIT** [comment]
I created a pull request to restructure the templates, but for safety i will do a test on a different temp repo sometimes the github features are available only to paid account

**Pull request closed without merging**
