### PR TITLE
Hr hr translation

### PR DESCRIPTION
**Pull request by arvvoid**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
I have changed/add other strings: 30006, 30103, 30240
Sorry for the delay but it was necessary, if you can update

**Comment by arvvoid** [comment]
Hello, no problem, will update today or tomorrow

**Comment by arvvoid** [comment]
Merged your changes from master will check the translations later and let you know with a message  here when I'm done.

WIP

**Comment by CastagnaIT** [comment]
well thanks

**Comment by arvvoid** [comment]
Ready :)

**Pull request merged**
