### PR TITLE
Add InputStream Helper settings to Expert category

### LINKED ISSUE #205: Better integration with inputstreamhelper
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
As one of the developers of **script.module.inputstreamhelper**, we recently refactored this add-on so it is easier to integrate it in 3rd party add-ons for troubleshooting.

Things you could integrate from your Settings menu:
- An information pane showing Kodi, InputStream and Widevine versions
- Open the InputStream Helper settings
- (Re)install Widevine CDM from the menu (could help with issues)

#### Describe the use case
We cannot guarantee that Widevine CDM will work perfectly in the future. There have been cases in the past where a new Widevine release broke a perfectly working system, or caused performance issues on some platforms.

Giving people access to version information and control over their Widevine installation may help in troubleshooting or fixing playback issues.

That said, the ultimate goal of InputStream Helper is that it stays out of the way. And that is still the goal, so it is up to you whether you want to give more information/control to your users (when things stop working).

Also see:
- https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/API
- https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration
- https://github.com/emilsvennesson/script.module.inputstreamhelper/issues

### PR DESCRIPTION
**Pull request by dagwieers**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
This adds the InputStream Helper settings to the Expert category of the
Netflix settings.

This fixes #205

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Everything is alright? you are no longer there lately..
do you plan to fix the commit?

**Comment by dagwieers** [comment]
@CastagnaIT You could have edited this PR and merged it instead.

**Comment by CastagnaIT** [comment]
I wasn't sure you would have followed the situation, you haven't answered for many days...

**Comment by dagwieers** [comment]
That doesn't matter. From a project management point-of-view, you can make edits to PRs and merge them if a contributor no longer replies. Also, it is IMO better if you don't allow direct commits to the master branch, but work through PRs for everything, so everything can be reviewed using the same process. If you don't want to do that, that's fine, I just think it is nicer in general.

That said I am glad this is merged, but I have no idea if/what you have changed from my original PR. So I do not feel responsible either :-)

**Comment by CastagnaIT** [comment]
next time i'll see how to try editing, i didn't know you could modify a pull request of another user throught shell
so i have only corrected some oversights in translations

**Comment by dagwieers** [comment]
No worries, I trust you. Just wanted to point this out.

**Pull request closed without merging**
