### PR TITLE
customize Main Menu

### PR DESCRIPTION
**Pull request by lekma**
## Types of changes

- [X] New feature (non-breaking change which adds functionality)

Adds a setting page to customize what is shown on the Main Menu

### CODE REVIEW

**Comment by lekma** [comment]
@CastagnaIT: interested?

**Comment by CastagnaIT** [comment]
this time you didn't make a good implementation, the idea is good but badly made..
not to be negative, but i have not replied because the time i lose to do the review is the time that i take to implement it by myself.
Leave here your pull request, i take it manually, i make the necessary changes and i join you as commit author

**Comment by lekma** [comment]
did you see the latest changes? if yes, your answer comes off as smug/arrogant... you must be fun at parties.

**Comment by CastagnaIT** [comment]
sadly missing beautiful women here.. no women no party hehe

**Comment by lekma** [comment]
wow! just wow!

**Pull request closed without merging**
