### PR TITLE
Update PL

### PR DESCRIPTION
**Pull request by notoco**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
a long birth now it is good😄

**Comment by notoco** [comment]
Well ... it's Friday evening. You probably drink wine in Italy, in Poland ... well ... we don't drink wine :)
I forgot to read the notes on what and how to do and I did it all from my memory ...

**Comment by CastagnaIT** [comment]
depends, usually I'm drinking beer on friday hehehe
what do you drink there?

**Comment by notoco** [comment]
Okocim - Polish beer

**Pull request merged**
