### PR TITLE
Login with authentication key file

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

In the last month due to login problems (new netflix protections?)
in many cases you can no longer possible to login through the add-on
with the result of "incorrect password" also when it is correct.
I suspect of a new google reCAPTCHA version protection, but nothing with certainty.
Issue: https://github.com/CastagnaIT/plugin.video.netflix/issues/502

This PR implement a new login method,
basically the user run a software on his computer called "NFAuthenticationKey"
that will generate a file called NFAuthentication.Key

HOW WORKS
This software will open the Chrome browser in incognito with the NF login page,
the user login as usual, and the software will generate the "NFAuthentication.Key" file.
The software NOT handle and can NOT read the credentials, it take only encrypted data.

With this file the user can login with the add-on in to his account,
and will be requested also to input your account password.

Some data protection precautions have been taken to the file NFAuthentication.Key:
- The file is protected
- The file expire in 5 day
- You can use it only if you have the PIN protection, provided dinamically by the software

I develop this software (NFAuthenticationKey) only for Windows systems,
others developers can use the source code (that i will publish soon)
to port the software to other operating systems,
by respecting the rules of protection.

### CODE REVIEW

**Comment by notoco** [comment]
If I do not have an error with logging in (box on 24/7) on coreelec, I do not log out, will I also have to use this uncomfortable solution? This scares me: The file expire in 1 day

**Comment by CastagnaIT** [comment]
This login mode is only for those who cannot login
it is uncomfortable but it is the only possible way
there is no other solutions, at least i could not find any...

the created file expires one day, for security reason and because the data contained can not have long longevity, so to avoid other side effects
after the login you can delete the file

**Comment by CastagnaIT** [comment]
I have raised the validity to 5 days

**Comment by emc02** [comment]
How can this Software be tested? Where can I get the file to execute?
Is it correct, that the NFAuthenticationKey runs only on windows, but the generated file can be used on all platforms for login?
Where to put the NFAuthentication.Key file and is there a Version of your plugin that can handle the file?

**Comment by pardalek73** [comment]
It don´t work for me. Plugin write - after I select key file and set PIN: "File is not a zip file".
Am I doing anything wrong?
(Android TV, Kodi 18, plugin.video.netflix_1.8.0_20200901)

**Comment by CastagnaIT** [comment]
@emc02 read the Issue thread opened for password issue
yes you can use the same generated file key on every type of device/system

**Comment by jlopez75** [comment]
Hi,

I installed the Netflix add-on on KODI. Unable to identify myself, I downloaded the authencation key. But when I want to open it I have the following error:

Error reading Jobject from JsonReader. Paht ", line 0, position 0.

Can you help me figure out the error?

Thank you

**Pull request merged**
