### PR TITLE
Fixed slow list creation on RaspberryPi devices by disabling the art …

### PR DESCRIPTION
**Pull request by xLAva**
…caching.

* the pure parse_art call is faster than the call into the cache (even if there is no cache miss)
** the cache call is more than 10x slower (even if it is non persistent)
* fixed timeouts on during list browsing (especially on longer lists)

### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
On my Kodi installation on a RaspberryPi4 I got constant timeouts during list browsing and it was way slower than it used to be.
I investigated a bit and found out that the art caching is super slow compared to not doing any caching (even the call into the cache without a miss is way slower)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
> ** the cache call is more than 10x slower 

welcome comparison log's with time measurements before/after

> (even if it is non persistent)

non-persistent cache are in memory operations, and are 10x slower?
this sound very strange

**Comment by xLAva** [comment]
Hi!

Thx for the feedback, I just re-tested it and you are right.
I must have mixed up some of my testing changes.

The only big effect I get now, is by moving all persistent caches to memory caches.
(FYI: It looks like these testing numbers have a change range of around 400ms if the exact same test is repeated) 

Tested on Raspi4 witch SDCard on a 40 entry list:
build_video_listing (caches empty) 267198ms 
build_video_listing (full cache) 3596ms

Tested the same list after changing all persistent caches to memory caches:
build_video_listing (caches empty) 4247ms 
build_video_listing (full cache) 3969ms

But what I can see, there is actually not much gain from the cache itself (on the Raspi 4 at least).
Tested with non-persistent caches on a 180 entry list:
build_video_listing (empty cache) 22248 ms
build_video_listing (full cache) 19489 ms

So is there a specific reason to have some caches on the disk? 
It seems it causes massive problems with slow disks.

I think it might be a good idea to either not make them persistent at all, or offer an option to have all caches in memory.
What do you think?

**Comment by CastagnaIT** [comment]
I did not have time to do testing
but your report is much useful

part of the current cache management is inherited from the oldest addon v14
many changes have been made over time
managing every part of the addon perfectly takes a long time 
and the consideration of as many cases as possible is difficult
would mean having all kinds of hardware of all kinds available and wasting a lot of time doing individual tests

the scope of the persistent cache is yes save the parsed data, in order to alive between each Kodi startup.
this to avoid elaborate every time same data and save time/cpu cycles
because the elaboration in some cases could be heavy for low end cpu's

here is what i want to explain:

> Tested the same list after changing all persistent caches to memory caches:
> build_video_listing (caches empty) 4247ms
> build_video_listing (full cache) 3969ms

this means about 278ms to cpu processes the parsing data

> But what I can see, there is actually not much gain from the cache itself (on the Raspi 4 at least).
> Tested with non-persistent caches on a 180 entry list:
> build_video_listing (empty cache) 22248 ms
> build_video_listing (full cache) 19489 ms

this means about 2,7 seconds  to cpu processes the parsing data, significant due to data increase so you can better understand the difference

in this case, if you have an high speed storage, you would save this 2,7 seconds of the cpu elaboration
and then load the list faster

you have to consider that the mass of users has fast storage and not slow storage
so disabling persistent storage would penalize the majority of the users (talking about low end cpus)

create a dedicated setting for this technical reason is not very good, find another compromise would be better
an idea can be find the best way to write all db changes in a single db transaction
in this way a single (or few) db writing should halve the times (in theory...)

**Comment by CastagnaIT** [comment]
This is an example of a idea of compromise
can you give me some test feedback?
[plugin.video.netflix_1.10.0_20201011_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/5360849/plugin.video.netflix_1.10.0_20201011_t1.zip)

if you look at the code in this way the slow writing operations are collected to the end
so you will benefit slow and fast storages types

**Comment by CastagnaIT** [comment]
@xLAva have you time to get me a feedback next days?

**Comment by xLAva** [comment]
The time numbers are all over the place.
I get today a way different result as last time. I'm not sure why. Maybe because the returned content from Netflix is different?

At least the numbers were consistent during the test.
I did the same test on the original 1.10 version, your test build and your test build, but with all non-persistent caches.


original cached cleared
build_video_listing took 166520ms (10x slower than non-persistent)

original cached
build_video_listing took 13143ms

1.10.0_20201011_t1 cached cleared
build_video_listing took 46901ms (2.8x slower than non-persistent)

1.10.0_20201011_t1 cached
build_video_listing took 14749ms

non-persistent cached cleared
build_video_listing took 16549ms

non-persistent cached
build_video_listing took 16000ms


As you can see it is way better, but it is still about 3 times slower than non-persistent caches.
It also is way over the 20s timeout limit for a small 40 entry list.

Something worries me about this new test round.
The original "cache cleared" run was way faster this time, but the cached access was way slower.

**Comment by xLAva** [comment]
I have new numbers.
A restart of my Kodi instance made everything way way faster.
It looks like the general performance goes down if Kodi is running for days.

Again tested on on Raspi4 witch SDCard on a 40 entry list:

original cached cleared
build_video_listing took 10251ms (61x slower than cache hit)

original cached
build_video_listing took 163ms

1.10.0_20201011_t1 cached cleared
build_video_listing took 1250ms (7x slower than cache hit)

1.10.0_20201011_t1 cached
build_video_listing took 168ms

So your change made a total cache miss nearly 10x faster, which is awesome.

**Comment by CastagnaIT** [comment]
Thanks for the report, a nice improvement,
what Class type is your SDCard?

**Comment by xLAva** [comment]
UHS Speed Class 1 (U1)
LibreELEC (9.2.5) Kodi 18.8

**Comment by CastagnaIT** [comment]
i think something not works with your SDCard
i have same U1 but 16gb of Kingston on same LibreElec version
but i do not have any speed problems

**Pull request closed without merging**
