### PR TITLE
Reworked PL translation

### PR DESCRIPTION
**Pull request by notoco**
### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
Completely corrected translation for the Polish language.
Polish has many possible translations for a given phrase, which, despite being correct, does not always fully reflect the meaning. This translation is to fix it

### CODE REVIEW

**Comment by CastagnaIT** [comment]
i wait to merge this,
until i merge the new rating system and also fix maturity level
so you can also include upcoming changes

**Comment by notoco** [comment]
ok I'll wait
So if you merge new rating system and fix maturity level to the master, I will have to rebase my (this) branch from the master and pull request?

**Comment by CastagnaIT** [comment]
yes alter you have to rebase with my new changes,
when you rebase git will warn you of conflicts to be resolved
so you update the translation, and then do a "forced push". no need open new pull request

i hope that tweimer reply otherwise we have to ask someone else in your country that helps..

**Comment by notoco** [comment]
In my country (Poland) Italy is asking you to do something for a German? Madness ... it's a joke, of course.

**Comment by CastagnaIT** [comment]
hahahaha :) now we look to the future.. the past can not change

**Comment by notoco** [comment]
we can't change, but we have to remember :) end off topic

**Comment by notoco** [comment]
Ok - I saw that you put these two patches to the master, so I did REBASE - but that's probably not the point. As I said, I'm not a programmer but a user - and GitHub overwhelms me over and over again.

**Comment by CastagnaIT** [comment]
so seem you have done all good
before the end, remember to fix typo in line 3
https://github.com/CastagnaIT/plugin.video.netflix/blob/ce0715fb0190ed9c462c2a933563bbe343a51426/resources/language/resource.language.pl_pl/strings.po#L3

**Comment by notoco** [comment]
Hurray! I think I managed to do it for the first time ... As Gianluca says (the only Italian in my family), a Pole with Italian always gets along - at the most you will need another bottle of vodka

**Comment by notoco** [comment]
something went wrong. comparing the version with which I did rebase I see the difference. I didn't get info about the conflict. However, I saw that in your last PR there have been changes in languages. and some texts are missing which I have to translate.

**Comment by CastagnaIT** [comment]
this PR is fine you don't need to make a new one, there are no more conflicts, just add the missing translations

**Comment by notoco** [comment]
Something got mixed up, only today it showed me (and here) that there is a conflict. Corrected. I'll add the missing phrases later.

**Comment by notoco** [comment]
Done

**Pull request merged**
