### PR TITLE
Add a release workflow

### LINKED ISSUE #853: Use the changelog for the GitHub release
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
It would be useful if the Netflix add-on releases in GitHub would get the changelog added so that people watching this project get releases with changelog in their mailbox. It would make it more useful to watch this project.

See: https://github.com/add-ons/plugin.video.vrt.nu/releases

If you like I can make a GitHub action that would automatically release and get the changelog entry from addon.xml into the official release. Then if you tag a commit, it would automatically make the release for you. This is how VRT NU is doing this. (It also pushes the release upstream for Krypton and Matrix, but that is not possible here)

### PR DESCRIPTION
**Pull request by dagwieers**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [ ] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
This will create a new release and adds the Changelog and Leia + Matrix
ZIP files to the release page whenever a new release is tagged and
pushed to the repository.

This fixes #853

### CODE REVIEW

**Comment by dagwieers** [comment]
@CastagnaIT You are going to love this. Most of the work was done by @mediaminister !

**Comment by CastagnaIT** [comment]
many thanks! to you and @mediaminister :)

sidenote:
addonchecker is not yet ready to matrix, i have ask to kodi dev to merge the fix for cryptodomex but is not included in to last pip release...

**Comment by dagwieers** [comment]
Ok, I reverted those changes. Feel free to merge now :-)

**Comment by dagwieers** [comment]
@CastagnaIT If you give me (temporary) access, I can add the Changelogs to previous releases as well.

**Comment by CastagnaIT** [comment]
yes ok

**Comment by dagwieers** [comment]
I updated all releases in GitHub with a changelog.
https://github.com/CastagnaIT/plugin.video.netflix/releases

PS On the frontpage you can get rid of the Packages section by editing it.

**Comment by CastagnaIT** [comment]
> I updated all releases in GitHub with a changelog.

thankyou it look good

> PS On the frontpage you can get rid of the Packages section by editing it.

done

**Pull request merged**
