### PR TITLE
Preparations for Kodi repo

### LINKED ISSUE #191: Add the Netflix add-on to the official Kodi repository
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
I don't know if this was ever proposed/discussed before, I surely could not find it here. But it would be nice if the Netflix add-on was part of the standard Kodi repository.

#### Describe the use case
So users find it in any Kodi installation, and existing users get updates without delay or manual effort.

#### Development tips
Simply send a PR to the leia branch of this repository and follow the rules.
https://github.com/xbmc/repo-plugins/tree/leia

### PR DESCRIPTION
**Pull request by dagwieers**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
These are the final changes for inclusion into the Kodi repository.

This fixes #191

### CODE REVIEW

**Comment by dagwieers** [comment]
This should not be merged until we have everything else sorted out.

**Comment by CastagnaIT** [comment]
Waiting for your confirmation to merge
i also still have to better understand how works all this changes

**Comment by dagwieers** [comment]
We haven't made any real changes to the add-on, and it should work as before. (It does for me)

You can try and run `make run` in your master branch on your local system to see if the integration tests work. (You may want to add a *test/userdata/credentials.json* with your username and password)

**Comment by dagwieers** [comment]
Sorry, the `make run` you have to do in the 'integration-tests` branch.

**Comment by dagwieers** [comment]
So now this PR also removes **enum34** and **mysql-connector-python**, but includes it in Travis.
(And adds it as a requirement for Kodi)

**Pull request closed without merging**
