### PR TITLE
Update Portuguese (Brazil)

### PR DESCRIPTION
**Pull request by mediabrasiltv**
Update Portuguese (Brazil) Translation.

@CastagnaIT, Kodi team added the "Portuguese (Brazil)" language code to the language code expander.

check here, no more need hack addon to recognize the language Portuguese (Brazil)

https://github.com/xbmc/xbmc/pull/17689

Was included in Leia too
https://github.com/xbmc/xbmc/commit/39e70a5b338a9f7be86c6c4ebb2b62fe7395e6b8

### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [ ] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Missing to update:
30006
30103
30240
30086
30124

**Comment by CastagnaIT** [comment]
> check here, no more need hack addon to recognize the language Portuguese (Brazil)

you talk about this? https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/common/kodiops.py#L221

so i should change it to:
'pt-BR': 'pb'

can you test? [plugin.video.netflix_1.2.0_20200420.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4504917/plugin.video.netflix_1.2.0_20200420.zip)

**Comment by MediaBrasil** [comment]
Thanks, I will test and finish the translations.

**Comment by mediabrasiltv** [comment]
Translated, a few it's only not used, one doesn´t exist 30240.

About your change don´t work, continue appear only Portuguese, in the past I used this in your addon to work here using the same code available now on Kodi

MSL.py file

xml = xml.replace('pt-BR', 'pob').replace('\n', '').replace('\r', '')

Now code changed a lot, I don´t know where insert, maybe the code above says something to you.

**Comment by CastagnaIT** [comment]
@mediabrasiltv you can't find them because you didn't compare the file with the original English file, add them

Found the problem, if you want test this:
[plugin.video.netflix_1.2.0_20200421.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4508324/plugin.video.netflix_1.2.0_20200421.zip)

**Comment by mediabrasiltv** [comment]
Yes, perfect now
https://i.imgur.com/uIHaXkp.jpg

I will compare strings to fix it.

**Comment by CastagnaIT** [comment]
your last commit have something of strange has reverted the previous commit

**Pull request closed without merging**
