### PR TITLE
Update Polish

### PR DESCRIPTION
**Pull request by notoco**
Update Polish to 1.2

### Check if this PR fulfills these requirements:
* [X] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [X] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [X] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [X] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [X] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by CastagnaIT** [comment]
please chech changes also for this ids:
30239,30215,30086,30124,30006,30103,30240

**Comment by notoco** [comment]
My fault. Something github-desktop got mixed up and didn't rebase completely ... I think he caught a virus ;)

**Comment by CastagnaIT** [comment]
only 30103 is not updated

**Comment by notoco** [comment]
;) Done

**Pull request merged**
