### PR TITLE
New cache management

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

The cache management currently used is fast but has too many critical issues
I looked at various existing script addons, but none were completely fit for purpose, some make use of 'repr' to convert data that is a _very bad thing to do_, others are no longer maintained, so i chose to centralize the access to the cache with a new custom service.

In summary:
- The management of the cache is now handled only by the service (no more by each client-frontend instance)
- The data is stored in-memory inside the service and with a dedicated database for the persistent storage (no more stored in Kodi homepage properties and hundreds of files and folders in the hdd)
- For devices that are always on, will clean the cache in a scheduled way, to free up memory
- The same cache data can be accessible between multiple instances at same time (service, user browser, script/ skin calls)
- The configuration for each cache bucket is cache_utils and no longer dispersed for each source code file, which made maintenance difficult

Hacks/workaround removed:
- No more stored in Kodi homepage properties with differents workarouds
- No more managed by more front-end instances, that cause side effects like cache locked/inacessible between instances
- No more cache bucket data load/commit at every addon run
- No more purge cache at every profile switch
- Removed SendSignal workaround to perform purge cache to the service side from the client instance
- Removed update "watched status" workaround `update_cache_videoid_runtime` (that sometime fails)

The access to the cache inside the service is done in a direct way
The access to the cache from a client instance to the service is done through an http service

For this reason in the future a nice thing would be to try to move the data processing performed by the front-end client instances to the service instance, it would speed up data access and remove a some overhead also for the library management (which is currently performed with a continuous exchange of instances, i don't know if it is cause by some limitation of Kodi will have to be verified)

✔ Moving building directories and loading lists to service
✔ Moving library sync / update to service

After this can be possible to fix also UpNext to make it to work with the watched status sync

### CODE REVIEW

**Comment by robotelro** [comment]
Any chance to make a setting to access the plugin in english not in the language selected in official app?

**Comment by CastagnaIT** [comment]
I don't understand, what's the connection with this PR?

**Comment by dagwieers** [comment]
If you would fix this branch and puch changes, you will see the new GitHub CI integration.

**Comment by dagwieers** [comment]
Hmm, we see all of them twice since this is also a branch on the same repository, let me fix that.

**Pull request merged**
