### PR TITLE
Parental control fix - load maturity levels dynamically

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Levels change by country and region, so it is not possible to make a static list.
To solve this, i perform a complete parse of the data from the web page

Examples:
Country like germany has different number of maturity levels towards italy or poland
and "adult" rating of poland is different from italy "adult" rating

Unfortunately, the descriptions will follow the language of the netflix profile and not that of the UI kodi, not so bad..

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@notoco @tweimer
If you can when you have time please test parental control settings:
[plugin.video.netflix_0.15.11_20191125_test.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/3887189/plugin.video.netflix_0.15.11_20191125_test.zip)

**Comment by tweimer** [comment]
This works.

**Comment by notoco** [comment]
It works. On skins other than the default ones (Aura, Arctic-Zephyr 2) there is a problem with keyboard support - the mouse succeeded - but the keyboard does not :(

**Comment by tweimer** [comment]
Yes, keyboard doesn't work for me too.

**Comment by CastagnaIT** [comment]
I forgot to update the ids for the focus..I'm gonna fix it now thanks!

**Pull request merged**
