### PR TITLE
Update spanish translation [es_ES]

### PR DESCRIPTION
**Pull request by roliverosc**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Translation

### CODE REVIEW

**Comment by boblo1** [comment]
@roliverosc : Are you going to read my comments on your translations before merging a commit or do you plan to work on your own?

**Comment by CastagnaIT** [comment]
FYI @roliverosc and @boblo1:
To @roliverosc: if possible in the future add a Tag boblo1 in the Translation PR to allow review your changes.

To @boblo1: If in the future you will learn how to use GitHub PR, you can take the situation by hand to make a more easy collaboration.
And you can also subscribe to https://github.com/add-ons/translations/issues/7 to understand when a new translation request will be done.

**Comment by roliverosc** [comment]
What? What comments? @boblo1

**Comment by boblo1** [comment]
> What? What comments? @boblo1

https://github.com/CastagnaIT/plugin.video.netflix/pull/748/files/415c6012ac8ea4754c887204a934cfc7bfa4ff12

**Comment by roliverosc** [comment]
@boblo1 sobre el pronombre tú = you para aplicaciones pienso que es más apropiado tratar al usuario de usted. Es más formal decir "introduzca" que "introduce".

**Comment by boblo1** [comment]
> @boblo1 sobre el pronombre tú = you para aplicaciones pienso que es más apropiado tratar al usuario de usted. Es más formal decir "introduzca" que "introduce" Aunque el traductor de google te lo traduzca como introduce. Y lo único que echo es completar la traducción ya que llevaba bastante tiempo pendiente de hacerse.

First, let me remind you English is the only language allowed in this place (unless the owner —CastagnaIT— states the otherwise). Keep in mind there could be people watching this thread and they could want to understand your reply, so please use our native language for private communications only (since there is no PM system in GitHub, you would have to use the email system or Kodi Forum PM system). If you need my email or want to send a PM in Kodi Forums (user @boblo), let me know and we will be able to talk in our language in a natural way.

Second, although you are right on the formal treatment, many  other Kodi addons use the informal way, so I think it would be better to use the informal way for more consistency with the addon ecosystem. The previous translation used the informal way, I know this well because I've been maintaining it for a while, so I think you changed the previous style. Finally, I think the formal treatment is more suitable for serious applications rather than entertainment addons for a multimedia center. In any case, major changes need a consensus.

Thanks for your reply.

**Comment by boblo1** [comment]
@roliverosc : Could you tell me something about this?

**Comment by roliverosc** [comment]
I think that the formal treatment could have a place in a plugin but I am used to using it in software translations and that's what i used to. Plex, Emby, Kodi tinymediamanager etc. Lately I am working on the skin translation and it is what I usually do.

**Pull request merged**
