### PR TITLE
Reimplemented "All Movies", "All TV shows", "Browse subgenres" menus and add search by genre/subgenre ID

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Due to problems with API shakty before it was not possible to get the LoCo lists of genres/subgenres,
now it's working again!

Ref. #683 

It has now also been possible to implement the search by genre/subgenre ID!😎
The codes are available on website links
or in the various websites that offer the code list

image

image

### CODE REVIEW

**Comment by notoco** [comment]
> It has now also been possible to implement the search by genre/subgenre ID!😎
The codes are available on website links
or in the various websites that offer the code list

Maybe it's worth thinking about some way to remember these codes - making your own list with your favorite categories

**Comment by CastagnaIT** [comment]
> some way to remember these codes

please elaborate

the search menu items are permanent saved
take in account that the ID's values are not static can change over the time

**Comment by notoco** [comment]
I didn't know ID's are variable - in that case it doesn't make sense.

**Comment by CastagnaIT** [comment]
yes the ID values are database references to group the videoid's
it would not be very appropriate to expose these values to users
but since it is now common practice we allow the use these ID's as fast shortcut

the genre/subgenres are like the Tag's, example (see _Genres:_ tags):

image

so netflix can add/remove these Tags to videos in any time
some old list of ID's of certain websites no longer work

**Pull request merged**
