### PR TITLE
New implementation of parental control settings

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improve functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description

Current implementation of adult pin (parental control) does not reflect account settings:
-its activation is separate from the management of the service
-its modification requires the PIN instead of the password
-not allow the settings to be changed
This PR reimplements parental control with a new settings window

Possible issue - edge case:
If kodi has already played more than one video (storing metadata in memory), and changes are made to the parental control externally (e.g. website) keeping Kodi running in the same time,
metadata in memory are not deleted causing new parental control settings not to be applied.
The user will have to remove the cache from the expert settings, or reboot Kodi.

#### Describe the new behavior

no change for users, changes to parental control will be reflected.

### Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Estochy label controls problem, unresolved
image

**Comment by tweimer** [comment]
@CastagnaIT I am missing "Older Teens [VM16]" amaturity level here. I can set it on Netflix.

**Comment by CastagnaIT** [comment]
i don't have Older Teens [VM16] on my netflix account...
post a screenshot

**Comment by tweimer** [comment]
Here it is. Maybe it depends on the country?

screenshot-www netflix com-2019 11

**Comment by CastagnaIT** [comment]
I missed this shitty netflix...is not the first time that it makes features distinctions between countries
what's your country?
i need you send to me a copy of part of your webpage:
Follow this steps with Google Chrome:
1 go to netflix webpage and enter to one profile
2 press F12 to open dev utils
3 On first tab page "Elements", press CTRL+F, below screen this open a text research
4 search "reactContext"
5 right click on the element (huge text) so Select COPY > COpy Element
6 Paste to a text file like notepad and attach here

**Comment by tweimer** [comment]
Here it is:
[netflix.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3876320/netflix.txt)

**Comment by notoco** [comment]
[netflix.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/3876389/netflix.txt)
Poland :)

**Comment by CastagnaIT** [comment]
i need another info, instruction here:
Follow this steps with Google Chrome:
1 go to netflix webpage and enter to Parental control page (screenshot above)
2 press F12 to open dev utils
3 Go to tab page "Network"
4 In the webpage, click on latest circle of the line (even if it is already selected)
5 In "Network" tab appear a new item on the list called "service", click on it
6 In the details to te right scroll down and take note of "maturityLevel"

Now click to the penultimate circle,
and repeat step 5, 6

thanks!

**Comment by notoco** [comment]
Poland
FireShot Capture 011 - Netflix - www netflix com
maturityLevel: 9999
maturityLevel: 100
maturityLevel: 80
maturityLevel: 41
maturityLevel: 0

**Comment by CastagnaIT** [comment]
good poland is same to my, change only text
now i wait tweimer response

**Comment by CastagnaIT** [comment]
@tweimer can you help again?

**Comment by tweimer** [comment]
Yes, wait a few days please.

**Comment by tweimer** [comment]
@CastagnaIT Try maturityLevel = 125 for "Older Teens" (16)

**Comment by CastagnaIT** [comment]
all others is same such as notoco write above?

**Comment by tweimer** [comment]
Yes.

**Comment by CastagnaIT** [comment]
thank you

**Pull request merged**
