### PR TITLE
Migration to new repository

### PR DESCRIPTION
**Pull request by CastagnaIT**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](../../master/Contributing.md) document.
* [x] I made sure there wasn't another [Pull Request](../../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which changes behaviour of an existing functionality)
- [ ] Improvement (non-breaking change which improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactor (non-breaking performance or readability improvements)

### Description

The repository has been changed,
we have to act a migration to the new addresses to allow get new updates

### CODE REVIEW

**Comment by ksooo** [comment]
Getting add-on startup error due to this change (macOS, Matrix):

```
2022-06-16 19:28:39.295 kodi.bin[11553:11285620] 2022-06-16 19:28:39.295 T:11285620   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: '1+matrix'
                                                   Traceback (most recent call last):
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/service.py", line 13, in <module>
                                                       run(sys.argv)
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/run_service.py", line 118, in run
                                                       check_service_upgrade()
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 53, in check_service_upgrade
                                                       _perform_service_changes(service_previous_ver, service_current_ver)
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/upgrade_controller.py", line 129, in _perform_service_changes
                                                       migrate_repository()
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/upgrade_actions.py", line 82, in migrate_repository
                                                       if CmpVersion(Addon('repository.castagnait').getAddonInfo('version')) >= '2.0.0':
                                                     File "/Users/kai/Library/Application Support/Kodi/addons/plugin.video.netflix/resources/lib/common/misc_utils.py", line 225, in __ge__
                                                       return operator.ge(*zip(*map(lambda x, y: (x or 0, y or 0),
                                                   ValueError: invalid literal for int() with base 10: '1+matrix'
                                                   -->End of Python script error report<--
                                                   ```

**Comment by CastagnaIT** [comment]
sh@t forgot to remove the version suffix used in matrix but not in nexus

**Comment by CastagnaIT** [comment]
wait 
now i checked git history of my repository 
but has never had `+matrix.1` in the version string
so seem you have a custom version of my repo

**Comment by ksooo** [comment]
> so seem you have a custom version of my repo

not that I know of.

**Comment by ksooo** [comment]
I solved the problem by downloading an installing https://github.com/CastagnaIT/repository.castagnait/blob/kodi/repository.castagnait-2.0.0.zip

**Pull request merged**
