### PR TITLE
Add more Dutch translations and fix English spelling

### PR DESCRIPTION
**Pull request by dagwieers**
### Check if this PR fulfills these requirements:
* [x] My changes respect the [Kodi add-on development rules](https://kodi.wiki/view/Add-on_rules)
* [x] I have read the [**CONTRIBUTING**](Contributing.md) document.
* [x] I made sure there wasn't another one [Pull Requests](../../pulls) opened for the same update/change
* [x] I have successfully tested my changes locally

#### Types of changes
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature change (non-breaking change which change behaviour of an existing functionality)
- [x] Improvement (non-breaking change which improve functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Description
This translates missing strings for the Dutch translations.

### CODE REVIEW

**Comment by Smeulf** [comment]
Just a few comments: 

30037: Isn't it better to translate it anyway?
You missed 30123, 30156 and 30157. On purpose?

**Comment by dagwieers** [comment]
To be honest, I had a lot of trouble translating various strings. Simply because it doesn't sound natural or clear when translated. I never use Dutch myself in menus or programs, but we don't have good translations for most English words.

For instance, the word "View", if I would translate it, I bet most people would have no clue what it is about. So in all honesty I think someone else that *does* use Dutch for things like this should review this (preferably after this is merged).

**Comment by Smeulf** [comment]
I understand what you mean, sometime I have the same problem :) I use to adapt to make it French haha.
Many thanks for the dutch speakers anyway.

**Comment by Smeulf** [comment]
I sometime look into Kodi's translations to see how a specific word was previously translated. That may help.

**Comment by CastagnaIT** [comment]
they don't seem complicated sentences😂
you don't have to translate 1:1

to 30037
you can use a word like/similar to the first option in the left panel (in your kodi language):
image

in the 30123, 30156 and 30157 I can try to reformulate them for you but, what do not you understand?

**Comment by CastagnaIT** [comment]
do you plan to add even the latest missing translations?
so then i could merge with the new release

**Comment by dagwieers** [comment]
@CastagnaIT I finished the translations.

**Comment by CastagnaIT** [comment]
yes but the name of commit do not respect the changes you made
you have changed more than one file languages
if you dont want to split in to more commit, so at least use an appropriate commit title/description
after this i do merge

**Comment by dagwieers** [comment]
@CastagnaIT If you click on squash/merge, you can edit the message and that's the one used in your history. So you can do this yourself on merge.

**Pull request merged**
